// components/inventory/InventoryPrintTemplate.tsx

import React, { forwardRef } from 'react';
import { useLanguage } from '@/contexts/LanguageContext';
import { cn, formatDate } from '@/lib/utils';

interface InventoryRecord {
  id: number;
  warehouse: {
    id: number;
    name: string;
    name_ar?: string;
  };
  product: {
    id: number;
    name: string;
    name_ar?: string;
    sku: string;
  };
  system_stock: number;
  counted_stock: number;
  difference: number;
  note: string | null;
  created_at: string;
}

interface InventoryPrintTemplateProps {
  data: {
    records: InventoryRecord[];
    warehouseName?: string;
    dateFrom?: string;
    dateTo?: string;
    createdAt?: string;
    totalRecords: number;
    totalSystemStock: number;
    totalCountedStock: number;
    totalDifference: number;
    positiveVariance: number;
    negativeVariance: number;
    zeroVariance: number;
  };
  companyInfo: {
    name: string;
    nameAr?: string;
    logo?: string;
    address?: string | null;
    addressAr?: string | null;
    phone?: string | null;
    email?: string;
    tax_id?: string | null;
    commercial_register?: string | null;
    website?: string | null;
  };
}

const InventoryPrintTemplate = forwardRef<HTMLDivElement, InventoryPrintTemplateProps>(
  ({ data, companyInfo }, ref) => {
    const { language } = useLanguage();
    const isRTL = language === 'ar';

    // نصوص ثابتة حسب اللغة
    const texts = {
      title: isRTL ? 'تقرير جرد المخزون' : 'Inventory Count Report',
      reportDate: isRTL ? 'تاريخ التقرير' : 'Report Date',
      warehouse: isRTL ? 'المخزن' : 'Warehouse',
      dateRange: isRTL ? 'الفترة' : 'Date Range',
      from: isRTL ? 'من' : 'From',
      to: isRTL ? 'إلى' : 'To',
      product: isRTL ? 'المنتج' : 'Product',
      
      sku: isRTL ? 'رمز المنتج' : 'SKU',
      systemStock: isRTL ? 'مخزون النظام' : 'System Stock',
      countedStock: isRTL ? 'المخزون المعدود' : 'Counted Stock',
      difference: isRTL ? 'الفرق' : 'Difference',
      note: isRTL ? 'ملاحظة' : 'Note',
      totalRecords: isRTL ? 'إجمالي السجلات' : 'Total Records',
      totalSystemStock: isRTL ? 'إجمالي مخزون النظام' : 'Total System Stock',
      totalCountedStock: isRTL ? 'إجمالي المخزون المعدود' : 'Total Counted Stock',
      totalDifference: isRTL ? 'إجمالي الفرق' : 'Total Difference',
      varianceSummary: isRTL ? 'ملخص الفروقات' : 'Variance Summary',
      positiveVariance: isRTL ? 'فائض' : 'Surplus',
      negativeVariance: isRTL ? 'عجز' : 'Shortage',
      zeroVariance: isRTL ? 'دقيق' : 'Accurate',
      phone: isRTL ? 'هاتف' : 'Phone',
      noData: isRTL ? 'لا توجد بيانات' : 'No data available',
      generatedBy: isRTL ? 'تم إنشاء التقرير بواسطة' : 'Report generated by',
      poweredBy: isRTL ? 'تم بواسطة Zain ERP' : 'Powered by Zain ERP',
      signature: isRTL ? 'توقيع المدير' : 'Manager Signature',
      date: isRTL ? 'التاريخ' : 'Date',
      allWarehouses: isRTL ? 'جميع المخازن' : 'All Warehouses',
    };

    // تنسيق الأرقام
    const formatNumber = (num: number) => {
      return num.toLocaleString(language === 'ar' ? 'ar-EG' : 'en-US');
    };

    // تنسيق الفرق مع علامة +/-
    const formatDifference = (diff: number) => {
      if (diff > 0) return `+${formatNumber(diff)}`;
      return formatNumber(diff);
    };

    // لون الفرق
    const getDifferenceColor = (diff: number) => {
      if (diff > 0) return 'text-green-600';
      if (diff < 0) return 'text-red-600';
      return 'text-gray-600';
    };

    return (
      <div
        ref={ref}
        className="bg-white text-black font-sans"
        style={{
          direction: isRTL ? 'rtl' : 'ltr',
          width: '210mm',
          minHeight: '297mm',
          margin: '0 auto',
          padding: '10mm',
          fontSize: '11px',
          lineHeight: '1.4'
        }}
      >
        {/* Header */}
        <div className="text-center border-b border-gray-300 pb-4 mb-4">
          {/* Logo */}
          {companyInfo.logo && (
            <div className="flex justify-center mb-2">
              <img
                src={companyInfo.logo}
                alt={companyInfo.name}
                className="h-16 w-auto object-contain"
              />
            </div>
          )}

          {/* Company Name */}
          <h1 className="text-xl font-bold text-black">
            {isRTL && companyInfo.nameAr ? companyInfo.nameAr : companyInfo.name}
          </h1>

          {/* Company Address */}
          {companyInfo.address && (
            <p className="text-xs text-gray-600 mt-1">
              {isRTL && companyInfo.addressAr ? companyInfo.addressAr : companyInfo.address}
            </p>
          )}

          {/* Company Phone & Tax ID */}
          <div className="flex justify-center gap-4 text-xs text-gray-500 mt-1">
            {companyInfo.phone && <span>{texts.phone}: {companyInfo.phone}</span>}
            {companyInfo.tax_id && <span>VAT: {companyInfo.tax_id}</span>}
          </div>

          {/* Report Title */}
          <h2 className="text-lg font-bold mt-3 text-primary">
            {texts.title}
          </h2>

          {/* Report Info */}
          <div className="flex justify-center gap-6 text-xs text-gray-600 mt-2">
            <div>
              <span className="font-semibold">{texts.reportDate}:</span>{' '}
              {formatDate(new Date().toISOString())}
            </div>
            <div>
              <span className="font-semibold">{texts.warehouse}:</span>{' '}
              {data.warehouseName || texts.allWarehouses}
            </div>
          </div>

          {/* Date Range */}
          {(data.dateFrom || data.dateTo) && (
            <div className="text-xs text-gray-600 mt-1">
              <span className="font-semibold">{texts.dateRange}:</span>{' '}
              {data.dateFrom ? `${texts.from} ${formatDate(data.dateFrom)}` : ''}
              {data.dateTo ? ` ${texts.to} ${formatDate(data.dateTo)}` : ''}
            </div>
          )}
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-5 gap-3 mb-6">
          <div className="bg-gray-50 p-3 rounded-lg text-center border border-gray-200">
            <p className="text-xs text-gray-500">{texts.totalRecords}</p>
            <p className="text-xl font-bold text-primary">{formatNumber(data.totalRecords)}</p>
          </div>
          <div className="bg-gray-50 p-3 rounded-lg text-center border border-gray-200">
            <p className="text-xs text-gray-500">{texts.totalSystemStock}</p>
            <p className="text-xl font-bold text-blue-600">{formatNumber(data.totalSystemStock)}</p>
          </div>
          <div className="bg-gray-50 p-3 rounded-lg text-center border border-gray-200">
            <p className="text-xs text-gray-500">{texts.totalCountedStock}</p>
            <p className="text-xl font-bold text-green-600">{formatNumber(data.totalCountedStock)}</p>
          </div>
          <div className="bg-gray-50 p-3 rounded-lg text-center border border-gray-200">
            <p className="text-xs text-gray-500">{texts.totalDifference}</p>
            <p className={cn("text-xl font-bold", getDifferenceColor(data.totalDifference))}>
              {formatDifference(data.totalDifference)}
            </p>
          </div>
          <div className="bg-gray-50 p-3 rounded-lg text-center border border-gray-200">
            <p className="text-xs text-gray-500">{texts.varianceSummary}</p>
            <div className="text-xs">
              <span className="text-green-600">+{data.positiveVariance}</span>
              <span className="mx-1">|</span>
              <span className="text-red-600">{data.negativeVariance}</span>
              <span className="mx-1">|</span>
              <span className="text-gray-600">{data.zeroVariance}</span>
            </div>
          </div>
        </div>

        {/* Items Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-xs border-collapse">
            <thead>
              <tr className="bg-gray-100 border-b-2 border-gray-300">
                <th className="py-2 px-2 text-center w-12">#</th>
                <th className="py-2 px-2 text-right">{texts.product}</th>
                <th className="py-2 px-2 text-center w-24">{texts.sku}</th>
                <th className="py-2 px-2 text-center w-20">{texts.systemStock}</th>
                <th className="py-2 px-2 text-center w-20">{texts.countedStock}</th>
                <th className="py-2 px-2 text-center w-20">{texts.difference}</th>
                <th className="py-2 px-2 text-right">{texts.note}</th>
              </tr>
            </thead>
            <tbody>
              {data.records.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-8 text-center text-gray-500">
                    {texts.noData}
                  </td>
                </tr>
              ) : (
                data.records.map((record, index) => (
                  <tr key={record.id} className="border-b border-gray-200 hover:bg-gray-50">
                    <td className="py-2 px-2 text-center">{index + 1}</td>
                    <td className="py-2 px-2 text-right">
                      <div className="font-medium">
                        {isRTL && record.product.name_ar ? record.product.name_ar : record.product.name}
                      </div>
                    </td>
                    <td className="py-2 px-2 text-center font-mono text-gray-600">
                      {record.product.sku}
                    </td>
                    <td className="py-2 px-2 text-center font-medium">
                      {formatNumber(record.system_stock)}
                    </td>
                    <td className="py-2 px-2 text-center font-medium">
                      {formatNumber(record.counted_stock)}
                    </td>
                    <td className="py-2 px-2 text-center">
                      <span className={cn("font-bold", getDifferenceColor(record.difference))}>
                        {formatDifference(record.difference)}
                      </span>
                    </td>
                    <td className="py-2 px-2 text-right text-gray-500">
                      {record.note || '-'}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Footer */}
        <div className="border-t border-gray-300 pt-4 mt-6">
          <div className="flex justify-between items-start">
            {/* Signature */}
            <div className="text-center">
              <div className="w-40 border-t border-gray-400 pt-1 mt-8">
                <p className="text-xs text-gray-500">{texts.signature}</p>
              </div>
            </div>

            {/* Generation Info */}
            <div className="text-right text-xs text-gray-500">
              <p>{texts.generatedBy}: {companyInfo.name}</p>
              <p>{texts.date}: {formatDate(new Date().toISOString())}</p>
            </div>
          </div>

          {/* Powered By */}
          <div className="text-center text-[9px] text-gray-400 mt-4">
            <p>{texts.poweredBy}</p>
          </div>
        </div>
      </div>
    );
  }
);

InventoryPrintTemplate.displayName = 'InventoryPrintTemplate';
export default InventoryPrintTemplate;