import { useEffect, useState } from 'react';
import { CarFront, CalendarDays, ClipboardList, Gauge, LogOut, RefreshCw, ShieldCheck, Wrench } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import api from '@/lib/api';

type PortalProps = { technician?: boolean };
type VisitForm = { vehicle_id: string; scheduled_at: string; type: string; purpose: string };
const statusLabels: Record<string, string> = { requested: 'طلب جديد', scheduled: 'مجدولة', checked_in: 'تم الوصول', completed: 'مكتملة', cancelled: 'ملغاة', diagnosis: 'تشخيص', in_progress: 'قيد التنفيذ', quality_check: 'فحص الجودة', ready_for_delivery: 'جاهزة للتسليم', delivered: 'تم التسليم' };
const statusClass = (status: string) => ['completed', 'delivered', 'ready_for_delivery'].includes(status) ? 'bg-emerald-100 text-emerald-800' : status === 'cancelled' ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800';

const Portal = ({ technician = false }: PortalProps) => {
  const tokenKey = technician ? 'technician_token' : 'customer_token';
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [token, setToken] = useState(localStorage.getItem(tokenKey)); const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(false);
  const [visitForm, setVisitForm] = useState<VisitForm>({ vehicle_id: '', scheduled_at: '', type: 'maintenance', purpose: '' });
  const loadDashboard = async () => { setLoading(true); try { const response = technician ? await Promise.all([api.get('/technician-portal/orders'), api.get('/technician-portal/visits')]) : [await api.get('/customer-portal/dashboard')]; setData(technician ? { orders: response[0].data.data, visits: response[1].data.data } : response[0].data.data); } catch { localStorage.removeItem(tokenKey); setToken(null); toast.error('انتهت جلسة الدخول، يرجى تسجيل الدخول مرة أخرى'); } finally { setLoading(false); } };
  useEffect(() => { if (token) void loadDashboard(); }, [token, technician]);
  const login = async () => { try { const response = await api.post(`/${technician ? 'technician' : 'customer'}-portal/login`, { email, password }); localStorage.setItem(tokenKey, response.data.token); setToken(response.data.token); toast.success('تم تسجيل الدخول بنجاح'); } catch { toast.error('البريد الإلكتروني أو كلمة المرور غير صحيحة'); } };
  const logout = () => { localStorage.removeItem(tokenKey); setToken(null); setData(null); };
  const updateItemStatus = async (orderId: number, itemId: number, status: string) => { try { await api.patch(`/technician-portal/orders/${orderId}/items/${itemId}/status`, { status }); toast.success('تم تحديث حالة الخدمة'); await loadDashboard(); } catch { toast.error('تعذر تحديث حالة الخدمة'); } };
  const updateVisit = async (visitId: number, payload: any) => { try { await api.patch('/technician-portal/visits/' + visitId, payload); toast.success('تم تحديث الزيارة'); await loadDashboard(); } catch (error: any) { toast.error(error?.response?.data?.message || 'تعذر تحديث الزيارة'); } };
  const uploadPhoto = async (orderId: number, file: File) => { try { const form = new FormData(); form.append('photo', file); form.append('stage', 'during'); form.append('customer_visible', '1'); await api.post(`/technician-portal/orders/${orderId}/photos`, form, { headers: { 'Content-Type': 'multipart/form-data' } }); toast.success('تم إرسال الصورة للعميل'); await loadDashboard(); } catch { toast.error('تعذر رفع الصورة'); } };
  const updateOrderStatus = async (orderId: number, status: string) => { try { await api.patch(`/technician-portal/orders/${orderId}/status`, { status }); toast.success('تم تحديث حالة السيارة'); await loadDashboard(); } catch (error: any) { toast.error(error?.response?.data?.message || 'تعذر تحديث الحالة'); } };
  const requestVisit = async () => { if (!visitForm.vehicle_id || !visitForm.scheduled_at) return toast.error('اختر السيارة وموعد الزيارة'); try { await api.post('/customer-portal/visits', { vehicle_id: Number(visitForm.vehicle_id), scheduled_at: new Date(visitForm.scheduled_at).toISOString(), type: visitForm.type, purpose: visitForm.purpose || undefined }); setVisitForm({ vehicle_id: '', scheduled_at: '', type: 'maintenance', purpose: '' }); toast.success('تم إرسال طلب الزيارة وسيتم تأكيده من المركز'); await loadDashboard(); } catch (error: any) { toast.error(error?.response?.data?.message || 'تعذر إرسال طلب الزيارة'); } };

  if (!token) return <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 p-6" dir="rtl"><Card className="w-full max-w-md border-white/10 bg-white/95 shadow-2xl"><CardHeader className="text-center"><div className="mx-auto mb-2 flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-600 text-white"><CarFront /></div><CardTitle className="text-2xl">{technician ? 'بوابة الفني' : 'بوابة العميل'}</CardTitle><p className="text-sm text-muted-foreground">تابع سياراتك وخدماتك ومواعيدك من مكان واحد</p></CardHeader><CardContent className="space-y-4"><div><Label>البريد الإلكتروني</Label><Input dir="ltr" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="name@example.com" /></div><div><Label>كلمة المرور</Label><Input dir="ltr" type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></div><Button className="w-full bg-emerald-600 hover:bg-emerald-700" onClick={() => void login()}>دخول البوابة</Button></CardContent></Card></div>;
  if (technician) {
    const orders = data?.orders || [];
    const visits = data?.visits || [];
    const activeOrders = orders.filter((o: any) => !['delivered', 'cancelled'].includes(o.status));
    const doneItems = orders.flatMap((o: any) => o.items || []).filter((item: any) => item.status === 'done').length;
    const totalItems = orders.flatMap((o: any) => o.items || []).length;
    const statusCounts = ['diagnosis', 'in_progress', 'ready_for_delivery'].map((status) => ({ status, count: orders.filter((o: any) => o.status === status).length }));
    const maxCount = Math.max(...statusCounts.map((item) => item.count), 1);
    return <div className="min-h-screen bg-slate-950 p-4 text-slate-100 md:p-8" dir="rtl"><div className="mx-auto max-w-7xl space-y-6">
      <Header title="لوحة عمل الفني" subtitle="تابع السيارات والزيارات والخدمات المسندة إليك" onRefresh={loadDashboard} onLogout={logout} loading={loading} />
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><TechStat icon={<CarFront />} label="السيارات النشطة" value={activeOrders.length} /><TechStat icon={<CalendarDays />} label="طلبات الزيارة" value={visits.filter((v: any) => ['requested', 'scheduled', 'reschedule_requested'].includes(v.status)).length} /><TechStat icon={<ClipboardList />} label="الخدمات المكتملة" value={`${doneItems}/${totalItems}`} /><TechStat icon={<Gauge />} label="إجمالي الأوامر" value={orders.length} /></div>
      <div className="grid gap-6 lg:grid-cols-3"><Card className="border-white/10 bg-slate-900 text-slate-100 lg:col-span-2"><CardHeader><CardTitle>مؤشر حالات السيارات</CardTitle></CardHeader><CardContent className="space-y-4">{statusCounts.map((item) => <div key={item.status}><div className="mb-1 flex justify-between text-sm"><span>{statusLabels[item.status]}</span><b>{item.count}</b></div><div className="h-4 rounded-full bg-slate-800"><div className="h-4 rounded-full bg-emerald-500 transition-all" style={{ width: `${Math.round((item.count / maxCount) * 100)}%` }} /></div></div>)}</CardContent></Card><Card className="border-white/10 bg-slate-900 text-slate-100"><CardHeader><CardTitle>ملخص الأداء</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div className="flex justify-between border-b border-white/10 pb-2"><span>نسبة إنجاز الخدمات</span><b>{totalItems ? Math.round((doneItems / totalItems) * 100) : 0}%</b></div><div className="flex justify-between border-b border-white/10 pb-2"><span>قيد التنفيذ</span><b>{orders.filter((o: any) => o.status === 'in_progress').length}</b></div><div className="flex justify-between"><span>جاهزة للتسليم</span><b>{orders.filter((o: any) => o.status === 'ready_for_delivery').length}</b></div></CardContent></Card></div>
      <Card className="border-amber-200/20 bg-slate-900 text-slate-100"><CardHeader><CardTitle>طلبات الزيارات</CardTitle></CardHeader><CardContent className="space-y-3">{visits.length === 0 && <Empty text="لا توجد طلبات زيارات حالياً" />}{visits.map((visit: any) => <div key={visit.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-slate-800 p-4"><div><b>{visit.customer?.name} · {visit.vehicle?.make} {visit.vehicle?.model}</b><p className="mt-1 text-sm text-slate-400">{visit.purpose || 'زيارة صيانة'} · {visit.scheduled_at || 'بدون موعد'}</p><span className={`mt-2 inline-block rounded-full px-2 py-1 text-xs ${statusClass(visit.status)}`}>{statusLabels[visit.status] || visit.status}</span></div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => void updateVisit(visit.id, { status: 'accepted' })}>قبول</Button><Button size="sm" variant="outline" onClick={() => { const next = window.prompt('اكتب الموعد الجديد بصيغة 2026-09-20 10:00'); if (next) void updateVisit(visit.id, { status: 'reschedule_requested', scheduled_at: next }); }}>طلب تغيير موعد</Button><Button size="sm" variant="secondary" onClick={() => void updateVisit(visit.id, { status: 'checked_in' })}>تم حضور العميل</Button></div></div>)}</CardContent></Card>
      <Card className="border-white/10 bg-slate-900 text-slate-100"><CardHeader><CardTitle>السيارات وأوامر العمل الحالية</CardTitle></CardHeader><CardContent className="space-y-4">{orders.length === 0 && <Empty text="لا توجد سيارات أو أوامر مسندة إليك" />}{orders.map((order: any) => <div key={order.id} className="rounded-2xl border border-white/10 bg-slate-800 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-emerald-400">{order.order_number}</p><h3 className="mt-1 text-xl font-bold">{order.vehicle?.make} {order.vehicle?.model}</h3><p className="text-sm text-slate-400">العميل: {order.customer?.name} · اللوحة: {order.vehicle?.plate_number || '—'}</p></div><span className={`rounded-full px-3 py-1 text-xs ${statusClass(order.status)}`}>{statusLabels[order.status] || order.status}</span></div><div className="mt-4 grid gap-2 md:grid-cols-3"><Button size="sm" variant={order.status === 'diagnosis' ? 'default' : 'outline'} onClick={() => void updateOrderStatus(order.id, 'diagnosis')}>1. تشخيص</Button><Button size="sm" variant={order.status === 'in_progress' ? 'default' : 'outline'} onClick={() => void updateOrderStatus(order.id, 'in_progress')}>2. قيد التنفيذ</Button><Button size="sm" variant={order.status === 'ready_for_delivery' ? 'default' : 'outline'} onClick={() => void updateOrderStatus(order.id, 'ready_for_delivery')}>3. جاهزة للتسليم</Button></div><div className="mt-4 space-y-2"><p className="text-sm font-semibold">الخدمات داخل الأمر</p>{(order.items || []).map((item: any) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-700 p-3 text-sm"><span>{item.service?.name || item.description}</span><Button size="sm" variant={item.status === 'done' ? 'secondary' : 'outline'} onClick={() => void updateItemStatus(order.id, item.id, item.status === 'done' ? 'in_progress' : 'done')}>{item.status === 'done' ? 'Done ✓' : 'تحديد Done'}</Button></div>)}</div><label className="mt-4 inline-block cursor-pointer rounded-lg border border-emerald-500/40 px-4 py-2 text-sm text-emerald-300">إرسال صورة للعميل<input className="hidden" type="file" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadPhoto(order.id, file); }} /></label></div>)}</CardContent></Card>
    </div></div>;
  }

  const vehicles = data?.vehicles || []; const orders = data?.orders || []; const warranties = data?.warranties || []; const visits = data?.visits || []; const invoices = data?.invoices || []; const customer = data?.customer; const openOrders = orders.filter((o: any) => !['delivered', 'cancelled'].includes(o.status)).length; const totalOutstanding = invoices.reduce((sum: number, i: any) => sum + Math.max(Number(i.total || 0) - Number(i.paid || 0), 0), 0);
  return <div className="min-h-screen bg-slate-50 p-4 md:p-8" dir="rtl"><div className="mx-auto max-w-7xl space-y-6"><Header title={`أهلاً ${customer?.name || 'بك'}`} subtitle="بوابة العميل للخدمات والصيانة" onRefresh={loadDashboard} onLogout={logout} loading={loading} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<CarFront />} label="سياراتي" value={vehicles.length} /><Stat icon={<ClipboardList />} label="أوامر مفتوحة" value={openOrders} /><Stat icon={<ShieldCheck />} label="الضمانات" value={warranties.length} /><Stat icon={<CalendarDays />} label="الزيارات" value={visits.length} /></div>

  <section><SectionTitle icon={<CarFront />} title="سياراتي وتفاصيلها" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{vehicles.length === 0 ? <Empty text="لا توجد سيارة مسجلة لهذا الحساب" /> : vehicles.map((v: any) => <Card key={v.id} className="overflow-hidden border-0 shadow-sm"><div className="h-2 bg-emerald-500" /><CardContent className="space-y-3 p-5"><div className="flex items-start justify-between"><div><h3 className="text-lg font-bold">{v.make} {v.model}</h3><p className="text-sm text-muted-foreground">{v.plate_number || 'بدون لوحة'}</p></div><CarFront className="text-emerald-600" /></div><div className="grid grid-cols-2 gap-2 text-sm"><Detail label="السنة" value={v.model_year || '—'} /><Detail label="VIN" value={v.vin || '—'} /><Detail label="اللون" value={v.color || '—'} /><Detail label="الممشى" value={`${Number(v.current_mileage || 0).toLocaleString()} كم`} /></div><p className="flex items-center gap-2 text-xs text-muted-foreground"><ClipboardList className="h-4 w-4" /> {v.service_orders_count || 0} أوامر خدمة</p></CardContent></Card>)}</div></section>

  <section><SectionTitle icon={<CalendarDays />} title="حجز زيارة جديدة" /><Card className="border-emerald-100 shadow-sm"><CardContent className="grid gap-4 p-5 md:grid-cols-4"><div><Label>السيارة</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={visitForm.vehicle_id} onChange={(e) => setVisitForm({ ...visitForm, vehicle_id: e.target.value })}><option value="">اختر السيارة</option>{vehicles.map((v: any) => <option key={v.id} value={v.id}>{v.make} {v.model} · {v.plate_number || 'بدون لوحة'}</option>)}</select></div><div><Label>موعد الزيارة</Label><Input className="mt-1" type="datetime-local" min={new Date().toISOString().slice(0, 16)} value={visitForm.scheduled_at} onChange={(e) => setVisitForm({ ...visitForm, scheduled_at: e.target.value })} /></div><div><Label>نوع الزيارة</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={visitForm.type} onChange={(e) => setVisitForm({ ...visitForm, type: e.target.value })}><option value="maintenance">صيانة دورية</option><option value="inspection">فحص</option><option value="repair">إصلاح عطل</option><option value="warranty">ضمان</option></select></div><div className="md:col-span-4"><Label>وصف الطلب</Label><Textarea className="mt-1" value={visitForm.purpose} onChange={(e) => setVisitForm({ ...visitForm, purpose: e.target.value })} placeholder="اكتب العطل أو الخدمة المطلوبة" /></div><div className="md:col-span-4 flex justify-end"><Button className="bg-emerald-600 hover:bg-emerald-700" onClick={() => void requestVisit()}>إرسال طلب الزيارة</Button></div></CardContent></Card></section>

  <div className="grid gap-6 lg:grid-cols-2"><section><SectionTitle icon={<Wrench />} title="الفنيون وأوامر الخدمة" /><Card><CardContent className="space-y-3 p-5">{orders.length === 0 ? <Empty text="لا توجد أوامر خدمة" /> : orders.map((o: any) => <div key={o.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between gap-3"><div><b>{o.order_number}</b><p className="mt-1 text-sm text-muted-foreground">{o.vehicle?.make} {o.vehicle?.model} · {o.total_amount || 0}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs ${statusClass(o.status)}`}>{statusLabels[o.status] || o.status}</span></div><div className="mt-3 space-y-1 text-sm">{(o.items || []).map((item: any) => <div key={item.id} className="flex justify-between rounded bg-slate-50 p-2"><span>{item.service?.name || item.description}</span><span className={`rounded-full px-2 py-0.5 text-xs ${statusClass(item.status)}`}>{statusLabels[item.status] || item.status}</span></div>)}</div><div className="mt-3 flex items-center gap-2 text-sm"><Wrench className="h-4 w-4 text-emerald-600" /><span>الفني: {o.technicians?.length ? o.technicians.map((t: any) => t.name).join('، ') : 'لم يتم التعيين بعد'}</span></div></div>)}</CardContent></Card></section><section><SectionTitle icon={<ShieldCheck />} title="الضمانات" /><Card><CardContent className="space-y-3 p-5">{warranties.length === 0 ? <Empty text="لا توجد ضمانات مسجلة" /> : warranties.map((w: any) => <div key={w.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between"><b>{w.policy_name}</b><span className={`rounded-full px-3 py-1 text-xs ${statusClass(w.status)}`}>{w.status}</span></div><p className="mt-2 text-sm text-muted-foreground">السيارة: {w.vehicle?.make} {w.vehicle?.model}</p><p className="mt-1 text-xs text-muted-foreground">من {w.starts_at || '—'} إلى {w.ends_at || 'مفتوح'}</p></div>)}</CardContent></Card></section></div>

  <div className="grid gap-6 lg:grid-cols-2"><section><SectionTitle icon={<CalendarDays />} title="سجل الزيارات" /><Card><CardContent className="space-y-3 p-5">{visits.length === 0 ? <Empty text="لا توجد زيارات مسجلة" /> : visits.map((v: any) => <div key={v.id} className="flex items-center justify-between rounded-xl border bg-white p-4"><div><b>{v.vehicle?.make} {v.vehicle?.model}</b><p className="mt-1 text-sm text-muted-foreground">{v.purpose || 'زيارة صيانة'} · {v.scheduled_at || 'بدون موعد'}</p></div><span className={`rounded-full px-3 py-1 text-xs ${statusClass(v.status)}`}>{statusLabels[v.status] || v.status}</span></div>)}</CardContent></Card></section><section><SectionTitle icon={<Gauge />} title="الفواتير والمبالغ المستحقة" /><Card><CardContent className="space-y-3 p-5"><div className="rounded-xl bg-slate-900 p-4 text-white"><p className="text-sm text-slate-300">إجمالي المستحق</p><p className="mt-1 text-2xl font-bold">{totalOutstanding.toLocaleString()} $</p></div>{invoices.map((i: any) => <div key={i.id} className="flex justify-between rounded-xl border p-3 text-sm"><span>{i.number || `فاتورة #${i.id}`}</span><span>{Number(i.total || 0).toLocaleString()} · {i.status}</span></div>)}</CardContent></Card></section></div>
  </div></div>;
};

const Header = ({ title, subtitle, onRefresh, onLogout, loading }: { title: string; subtitle?: string; onRefresh: () => Promise<void>; onLogout: () => void; loading: boolean }) => <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-emerald-600">Automotive Service Center</p><h1 className="text-3xl font-bold text-slate-900">{title}</h1>{subtitle && <p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>}</div><div className="flex gap-2"><Button variant="outline" onClick={() => void onRefresh()} disabled={loading}><RefreshCw className={`ml-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} /> تحديث</Button><Button variant="outline" onClick={onLogout}><LogOut className="ml-2 h-4 w-4" /> خروج</Button></div></div>;
const TechStat = ({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) => <Card className="border-white/10 bg-slate-900 text-slate-100"><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-slate-400">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div><div className="rounded-xl bg-emerald-500/10 p-3 text-emerald-400">{icon}</div></CardContent></Card>;
const SectionTitle = ({ icon, title }: { icon: React.ReactNode; title: string }) => <h2 className="mb-3 flex items-center gap-2 text-xl font-bold text-slate-800">{icon}<span>{title}</span></h2>;
const Stat = ({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) => <Card className="border-0 shadow-sm"><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div><div className="rounded-xl bg-emerald-50 p-3 text-emerald-600">{icon}</div></CardContent></Card>;
const Detail = ({ label, value }: { label: string; value: string | number }) => <div className="rounded-lg bg-slate-50 p-2"><p className="text-[11px] text-muted-foreground">{label}</p><p className="truncate text-sm font-medium" dir={label === 'VIN' ? 'ltr' : undefined}>{value}</p></div>;
const Empty = ({ text }: { text: string }) => <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div>;
export const CustomerPortal = () => <Portal />;
export const TechnicianPortal = () => <Portal technician />;
export default Portal;
