import { useState } from 'react';
import { Link } from 'react-router-dom';
import MainLayout from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Factory, Play, CheckCircle2, Boxes, Plus, X, Settings2 } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '@/lib/api';
import { toast } from 'sonner';

const steps = ['أمر إنتاج', 'صرف الخامات', 'تشغيل', 'فحص الجودة', 'إضافة المنتج التام', 'قيد التكلفة'];
const emptyOrder = { product_id: '', bom_id: '', warehouse_id: '', planned_quantity: '', planned_start_date: '', planned_end_date: '', planned_cost: '', notes: '' };
type ApiError = { response?: { data?: { message?: string } } };
type ManufacturingOrder = { id: number; order_number: string; status: string; planned_quantity: number; produced_quantity?: number; actual_cost?: number; product?: { name?: string }; bom?: { code?: string } };

export default function Manufacturing() {
  const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [orderForm, setOrderForm] = useState(emptyOrder);
  const [completeForm, setCompleteForm] = useState({ produced_quantity: '', warehouse_id: '', inventory_account_id: '', work_in_progress_account_id: '' });
  const { data, isLoading } = useQuery({ queryKey: ['manufacturing-dashboard'], queryFn: async () => (await api.get('/manufacturing/dashboard')).data.data });
  const createMutation = useMutation({ mutationFn: () => api.post('/manufacturing/orders', { ...orderForm, product_id: Number(orderForm.product_id), bom_id: orderForm.bom_id ? Number(orderForm.bom_id) : null, warehouse_id: orderForm.warehouse_id ? Number(orderForm.warehouse_id) : null, planned_quantity: Number(orderForm.planned_quantity), planned_cost: Number(orderForm.planned_cost || 0) }), onSuccess: () => { toast.success('تم إنشاء أمر الإنتاج'); setOrderForm(emptyOrder); setShowCreate(false); queryClient.invalidateQueries({ queryKey: ['manufacturing-dashboard'] }); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر إنشاء أمر الإنتاج') });
  const startMutation = useMutation({ mutationFn: (id: number) => api.post(`/manufacturing/orders/${id}/start`), onSuccess: () => { toast.success('تم تشغيل أمر الإنتاج'); queryClient.invalidateQueries({ queryKey: ['manufacturing-dashboard'] }); } });
  const completeMutation = useMutation({ mutationFn: (id: number) => api.post(`/manufacturing/orders/${id}/complete`, { ...completeForm, produced_quantity: Number(completeForm.produced_quantity), warehouse_id: Number(completeForm.warehouse_id), inventory_account_id: Number(completeForm.inventory_account_id), work_in_progress_account_id: Number(completeForm.work_in_progress_account_id), quality_status: 'passed' }), onSuccess: () => { toast.success('تم صرف الخامات وإضافة المنتج وترحيل القيد'); setSelectedId(null); queryClient.invalidateQueries({ queryKey: ['manufacturing-dashboard'] }); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر إكمال الأمر') });
  const orders = data?.orders?.data || [];
  return <MainLayout><div className="space-y-6" dir="rtl">
    <div className="rounded-2xl bg-gradient-to-l from-[#101a3b] to-[#5b21b6] p-6 text-white"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><Factory size={32} /><div><h1 className="text-2xl font-extrabold">تشغيل المصانع</h1><p className="text-violet-100">دورة كاملة من BOM وصرف الخامات حتى المنتج التام والقيد المالي.</p></div></div><div className="flex flex-wrap gap-2"><Link to="/manufacturing/setup"><Button variant="outline" className="border-white/40 bg-white/10 text-white hover:bg-white/20"><Settings2 size={16} /> إدارة BOM والمراكز</Button></Link><Button onClick={() => setShowCreate(v => !v)} className="bg-white text-violet-800 hover:bg-violet-50"><Plus size={16} /> أمر إنتاج جديد</Button></div></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[['أوامر قيد التشغيل', data?.in_progress || 0], ['حجز جودة', data?.quality_hold || 0], ['BOM فعالة', data?.boms_count || 0], ['مراكز العمل', data?.work_centers_count || 0]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-white/10 p-3"><p className="text-xs text-violet-100">{label}</p><p className="text-2xl font-bold">{value}</p></div>)}</div></div>
    {showCreate && <Card><CardHeader><CardTitle className="flex items-center justify-between">إنشاء أمر إنتاج <Button variant="ghost" size="icon" onClick={() => setShowCreate(false)}><X size={16} /></Button></CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><Input placeholder="Product ID" type="number" value={orderForm.product_id} onChange={e => setOrderForm({ ...orderForm, product_id: e.target.value })} /><Input placeholder="BOM ID (اختياري)" type="number" value={orderForm.bom_id} onChange={e => setOrderForm({ ...orderForm, bom_id: e.target.value })} /><Input placeholder="Warehouse ID" type="number" value={orderForm.warehouse_id} onChange={e => setOrderForm({ ...orderForm, warehouse_id: e.target.value })} /><Input placeholder="الكمية المخططة" type="number" min="0.01" value={orderForm.planned_quantity} onChange={e => setOrderForm({ ...orderForm, planned_quantity: e.target.value })} /></div><div className="mt-3 grid gap-3 md:grid-cols-3"><Input type="date" value={orderForm.planned_start_date} onChange={e => setOrderForm({ ...orderForm, planned_start_date: e.target.value })} /><Input type="date" value={orderForm.planned_end_date} onChange={e => setOrderForm({ ...orderForm, planned_end_date: e.target.value })} /><Input placeholder="التكلفة المخططة" type="number" value={orderForm.planned_cost} onChange={e => setOrderForm({ ...orderForm, planned_cost: e.target.value })} /></div><Button className="mt-4" onClick={() => createMutation.mutate()} disabled={createMutation.isPending || !orderForm.product_id || !orderForm.planned_quantity}>حفظ أمر الإنتاج</Button></CardContent></Card>}
    <Card><CardHeader><CardTitle>خطوات التشغيل المترابطة</CardTitle></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-6">{steps.map((step, index) => <div key={step} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary text-primary-foreground">{index + 1}</span>{step}</div>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle>أوامر الإنتاج</CardTitle></CardHeader><CardContent>{isLoading ? <p>جاري التحميل...</p> : orders.length === 0 ? <p className="py-8 text-center text-muted-foreground">لا توجد أوامر إنتاج حتى الآن</p> : <div className="space-y-3">{orders.map((order: ManufacturingOrder) => <div key={order.id} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_1fr_1fr_auto] md:items-center"><div><p className="font-bold">{order.order_number}</p><p className="text-sm text-muted-foreground">{order.product?.name || 'منتج'} · المطلوب {order.planned_quantity}</p></div><div><Badge>{order.status}</Badge><p className="mt-2 text-xs text-muted-foreground">التكلفة الفعلية: {order.actual_cost || 0}</p></div><div className="text-sm">{order.bom?.code || 'بدون BOM'}<p className="text-xs text-muted-foreground">الإنتاج: {order.produced_quantity || 0}</p></div><div className="flex flex-wrap gap-2">{['draft', 'planned'].includes(order.status) && <Button size="sm" onClick={() => startMutation.mutate(order.id)}><Play size={15} /> تشغيل</Button>}{['in_progress', 'quality_hold'].includes(order.status) && <Button size="sm" variant="secondary" onClick={() => setSelectedId(order.id)}><CheckCircle2 size={15} /> إكمال وترحيل</Button>}</div></div>)}</div>}</CardContent></Card>
    {selectedId && <Card className="border-primary"><CardHeader><CardTitle><Boxes size={20} className="inline me-2" /> إكمال أمر الإنتاج #{selectedId}</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><Input placeholder="الكمية المنتجة" type="number" value={completeForm.produced_quantity} onChange={e => setCompleteForm({ ...completeForm, produced_quantity: e.target.value })} /><Input placeholder="Warehouse ID" type="number" value={completeForm.warehouse_id} onChange={e => setCompleteForm({ ...completeForm, warehouse_id: e.target.value })} /><Input placeholder="حساب المخزون ID" type="number" value={completeForm.inventory_account_id} onChange={e => setCompleteForm({ ...completeForm, inventory_account_id: e.target.value })} /><Input placeholder="حساب تحت التشغيل ID" type="number" value={completeForm.work_in_progress_account_id} onChange={e => setCompleteForm({ ...completeForm, work_in_progress_account_id: e.target.value })} /></div><div className="mt-4 flex gap-2"><Button onClick={() => completeMutation.mutate(selectedId)} disabled={completeMutation.isPending || !completeForm.produced_quantity}>ترحيل المخزون والقيد</Button><Button variant="outline" onClick={() => setSelectedId(null)}>إلغاء</Button></div></CardContent></Card>}
  </div></MainLayout>;
}
