import { useState } from 'react';
import MainLayout from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { HardHat, FileCheck2, Wallet, TrendingUp, ClipboardList, Link2, Plus, X, ListTree, Gauge, Trash2 } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '@/lib/api';
import { toast } from 'sonner';

const steps = ['العقد', 'WBS والميزانية', 'المشتريات والتكلفة', 'قياس الإنجاز', 'المستخلص', 'الاعتماد والتحصيل'];
const emptyProject = { name: '', customer_id: '', contract_number: '', start_date: '', planned_end_date: '', contract_value: '', budget_cost: '', retention_percent: '0', scope: '' };
const emptyWbs = { code: '', name: '', unit: '', planned_quantity: '', unit_price: '', planned_cost: '' };
type ApiError = { response?: { data?: { message?: string } } };
type ProjectRow = { id: number; project_code: string; name: string; status: string; contract_value?: number; actual_cost?: number; budget_cost?: number; customer?: { name?: string } };
type WbsItem = { id: number; code: string; name: string; unit?: string; planned_quantity: number; unit_price: number; planned_cost: number; completed_quantity: number; completion_percent: number };
type ClaimLine = { wbs_item_id: number; quantity: number };

export default function Projects() {
  const queryClient = useQueryClient();
  const [costProjectId, setCostProjectId] = useState<number | null>(null);
  const [claimProjectId, setClaimProjectId] = useState<number | null>(null);
  const [wbsProjectId, setWbsProjectId] = useState<number | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [project, setProject] = useState(emptyProject);
  const [wbs, setWbs] = useState(emptyWbs);
  const [progress, setProgress] = useState<Record<number, string>>({});
  const [claimLines, setClaimLines] = useState<ClaimLine[]>([]);
  const [cost, setCost] = useState({ cost_type: 'material', amount: '', debit_account_id: '', credit_account_id: '' });
  const [claim, setClaim] = useState({ gross_amount: '', advance_deduction: '0', retention_amount: '0' });
  const { data, isLoading } = useQuery({ queryKey: ['projects-dashboard'], queryFn: async () => (await api.get('/projects/dashboard')).data.data });
  const { data: wbsItems = [], isLoading: loadingWbs } = useQuery<WbsItem[]>({ queryKey: ['project-wbs', wbsProjectId], enabled: Boolean(wbsProjectId), queryFn: async () => (await api.get(`/projects/${wbsProjectId}/wbs`)).data.data || [] });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ['projects-dashboard'] }); queryClient.invalidateQueries({ queryKey: ['project-wbs'] }); };
  const createMutation = useMutation({ mutationFn: () => api.post('/projects', { ...project, customer_id: project.customer_id ? Number(project.customer_id) : null, contract_value: Number(project.contract_value || 0), budget_cost: Number(project.budget_cost || 0), retention_percent: Number(project.retention_percent || 0) }), onSuccess: () => { toast.success('تم إنشاء المشروع'); setProject(emptyProject); setShowCreate(false); refresh(); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر إنشاء المشروع') });
  const costMutation = useMutation({ mutationFn: (id: number) => api.post(`/projects/${id}/costs`, { ...cost, amount: Number(cost.amount), debit_account_id: Number(cost.debit_account_id), credit_account_id: Number(cost.credit_account_id) }), onSuccess: () => { toast.success('تم تسجيل تكلفة المشروع وترحيل القيد'); setCostProjectId(null); refresh(); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر تسجيل التكلفة') });
  const createWbsMutation = useMutation({ mutationFn: () => api.post(`/projects/${wbsProjectId}/wbs`, { ...wbs, planned_quantity: Number(wbs.planned_quantity), unit_price: Number(wbs.unit_price), planned_cost: Number(wbs.planned_cost || Number(wbs.planned_quantity) * Number(wbs.unit_price)) }), onSuccess: () => { toast.success('تم إضافة بند الأعمال'); setWbs(emptyWbs); refresh(); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر إضافة البند') });
  const progressMutation = useMutation({ mutationFn: ({ id, quantity }: { id: number; quantity: string }) => api.post(`/projects/${wbsProjectId}/wbs/${id}/progress`, { completed_quantity: Number(quantity) }), onSuccess: () => { toast.success('تم تحديث قياس الإنجاز'); refresh(); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر تحديث الإنجاز') });
  const deleteWbsMutation = useMutation({ mutationFn: (id: number) => api.delete(`/projects/${wbsProjectId}/wbs/${id}`), onSuccess: () => { toast.success('تم حذف بند الأعمال'); refresh(); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'لا يمكن حذف هذا البند') });
  const claimMutation = useMutation({ mutationFn: (id: number) => api.post(`/projects/${id}/claims`, { gross_amount: claimLines.length ? undefined : Number(claim.gross_amount), items: claimLines.length ? claimLines : undefined, advance_deduction: Number(claim.advance_deduction), retention_amount: Number(claim.retention_amount) }), onSuccess: () => { toast.success('تم إنشاء المستخلص وربطه ببنود الأعمال'); setClaimProjectId(null); setClaimLines([]); refresh(); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر إنشاء المستخلص') });
  const projects = data?.projects?.data || [];
  return <MainLayout><div className="space-y-6" dir="rtl">
    <div className="rounded-2xl bg-gradient-to-l from-[#101a3b] to-[#c2410c] p-6 text-white"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><HardHat size={32} /><div><h1 className="text-2xl font-extrabold">المقاولات والمشروعات</h1><p className="text-orange-100">العقد، BOQ/WBS، الإنجاز، التكلفة، المستخلص والتحصيل في دورة واحدة.</p></div></div><Button onClick={() => setShowCreate(v => !v)} className="bg-white text-orange-800 hover:bg-orange-50"><Plus size={16} /> مشروع جديد</Button></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-5">{[['مشروعات نشطة', data?.active_count || 0], ['قيمة العقود', data?.contract_value || 0], ['الميزانية', data?.budget_cost || 0], ['التكلفة الفعلية', data?.actual_cost || 0], ['مستخلصات معلقة', data?.pending_claims || 0]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-white/10 p-3"><p className="text-xs text-orange-100">{label}</p><p className="text-xl font-bold">{value}</p></div>)}</div></div>
    {showCreate && <Card><CardHeader><CardTitle className="flex items-center justify-between">إنشاء مشروع جديد <Button variant="ghost" size="icon" onClick={() => setShowCreate(false)}><X size={16} /></Button></CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><Input placeholder="اسم المشروع" value={project.name} onChange={e => setProject({ ...project, name: e.target.value })} /><Input placeholder="Customer ID اختياري" type="number" value={project.customer_id} onChange={e => setProject({ ...project, customer_id: e.target.value })} /><Input placeholder="رقم العقد" value={project.contract_number} onChange={e => setProject({ ...project, contract_number: e.target.value })} /><Input placeholder="قيمة العقد" type="number" value={project.contract_value} onChange={e => setProject({ ...project, contract_value: e.target.value })} /></div><div className="mt-3 grid gap-3 md:grid-cols-4"><Input type="date" value={project.start_date} onChange={e => setProject({ ...project, start_date: e.target.value })} /><Input type="date" value={project.planned_end_date} onChange={e => setProject({ ...project, planned_end_date: e.target.value })} /><Input placeholder="الميزانية" type="number" value={project.budget_cost} onChange={e => setProject({ ...project, budget_cost: e.target.value })} /><Input placeholder="نسبة الاحتجاز" type="number" value={project.retention_percent} onChange={e => setProject({ ...project, retention_percent: e.target.value })} /></div><Button className="mt-4" onClick={() => createMutation.mutate()} disabled={createMutation.isPending || !project.name}>حفظ المشروع</Button></CardContent></Card>}
    <Card><CardHeader><CardTitle>دورة المشروع المترابطة</CardTitle></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-6">{steps.map((step, index) => <div key={step} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary text-primary-foreground">{index + 1}</span>{step}</div>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle>المشروعات</CardTitle></CardHeader><CardContent>{isLoading ? <p>جاري التحميل...</p> : projects.length === 0 ? <p className="py-8 text-center text-muted-foreground">لا توجد مشروعات حتى الآن</p> : <div className="space-y-3">{projects.map((item: ProjectRow) => <div key={item.id} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1.2fr_1fr_1fr_auto_auto_auto] md:items-center"><div><p className="font-bold">{item.project_code} · {item.name}</p><p className="text-sm text-muted-foreground">العميل: {item.customer?.name || '-'}</p></div><div><Badge>{item.status}</Badge><p className="mt-2 text-xs text-muted-foreground">عقد: {item.contract_value || 0}</p></div><div><p className="text-sm">التكلفة: {item.actual_cost || 0}</p><p className="text-xs text-muted-foreground">الميزانية: {item.budget_cost || 0}</p></div><Button size="sm" variant="outline" onClick={() => setWbsProjectId(item.id)}><ListTree size={15} /> WBS</Button><Button size="sm" variant="secondary" onClick={() => setCostProjectId(item.id)}><Wallet size={15} /> تكلفة</Button><Button size="sm" onClick={() => { setClaimProjectId(item.id); setClaimLines([]); }}><FileCheck2 size={15} /> مستخلص</Button></div>)}</div>}</CardContent></Card>
    {wbsProjectId && <Card className="border-primary"><CardHeader><CardTitle className="flex items-center justify-between"><span className="flex items-center gap-2"><ListTree size={20} /> BOQ / WBS للمشروع #{wbsProjectId}</span><Button variant="ghost" size="icon" onClick={() => setWbsProjectId(null)}><X size={16} /></Button></CardTitle></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-6"><Input placeholder="كود البند" value={wbs.code} onChange={e => setWbs({ ...wbs, code: e.target.value })} /><Input placeholder="اسم البند" value={wbs.name} onChange={e => setWbs({ ...wbs, name: e.target.value })} /><Input placeholder="الوحدة" value={wbs.unit} onChange={e => setWbs({ ...wbs, unit: e.target.value })} /><Input placeholder="الكمية المخططة" type="number" value={wbs.planned_quantity} onChange={e => setWbs({ ...wbs, planned_quantity: e.target.value })} /><Input placeholder="سعر الوحدة" type="number" value={wbs.unit_price} onChange={e => setWbs({ ...wbs, unit_price: e.target.value })} /><Button onClick={() => createWbsMutation.mutate()} disabled={createWbsMutation.isPending || !wbs.code || !wbs.name || !wbs.planned_quantity}><Plus size={15} /> إضافة بند</Button></div><div className="mt-4 space-y-2">{loadingWbs ? <p>جاري تحميل البنود...</p> : wbsItems.length === 0 ? <p className="py-5 text-center text-muted-foreground">لم تتم إضافة بنود أعمال</p> : wbsItems.map(item => <div key={item.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[1fr_1.5fr_0.8fr_0.8fr_1fr_auto] md:items-center"><div className="font-semibold">{item.code}</div><div>{item.name}<p className="text-xs text-muted-foreground">{item.unit || 'وحدة'} · المخطط {item.planned_quantity}</p></div><div>سعر: {item.unit_price}</div><div><Badge variant={item.completion_percent >= 100 ? 'default' : 'secondary'}>{Number(item.completion_percent).toFixed(1)}%</Badge></div><div className="flex items-center gap-1"><Input className="h-8" type="number" min="0" max={item.planned_quantity} value={progress[item.id] ?? item.completed_quantity} onChange={e => setProgress({ ...progress, [item.id]: e.target.value })} /><Button size="icon" variant="outline" title="حفظ الإنجاز" onClick={() => progressMutation.mutate({ id: item.id, quantity: progress[item.id] ?? String(item.completed_quantity) })}><Gauge size={14} /></Button></div><div className="flex gap-1"><Button size="sm" variant="outline" onClick={() => { setClaimProjectId(wbsProjectId); setClaimLines([{ wbs_item_id: item.id, quantity: Number(item.completed_quantity) }]); }}>للمستخلص</Button><Button size="icon" variant="ghost" onClick={() => deleteWbsMutation.mutate(item.id)}><Trash2 size={15} /></Button></div></div>)}</div></CardContent></Card>}
    {costProjectId && <Card className="border-primary"><CardHeader><CardTitle><ClipboardList size={20} className="inline me-2" /> تسجيل تكلفة للمشروع #{costProjectId}</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><Input placeholder="نوع التكلفة" value={cost.cost_type} onChange={e => setCost({ ...cost, cost_type: e.target.value })} /><Input placeholder="القيمة" type="number" value={cost.amount} onChange={e => setCost({ ...cost, amount: e.target.value })} /><Input placeholder="الحساب المدين ID" type="number" value={cost.debit_account_id} onChange={e => setCost({ ...cost, debit_account_id: e.target.value })} /><Input placeholder="الحساب الدائن ID" type="number" value={cost.credit_account_id} onChange={e => setCost({ ...cost, credit_account_id: e.target.value })} /></div><div className="mt-4 flex gap-2"><Button onClick={() => costMutation.mutate(costProjectId)} disabled={costMutation.isPending || !cost.amount}>حفظ وترحيل التكلفة</Button><Button variant="outline" onClick={() => setCostProjectId(null)}>إلغاء</Button></div></CardContent></Card>}
    {claimProjectId && <Card className="border-orange-500"><CardHeader><CardTitle className="flex items-center justify-between"><span className="flex items-center gap-2"><FileCheck2 size={20} /> إنشاء مستخلص</span><Button variant="ghost" size="icon" onClick={() => setClaimProjectId(null)}><X size={16} /></Button></CardTitle></CardHeader><CardContent><p className="mb-3 text-sm text-muted-foreground">{claimLines.length ? `تم ربط ${claimLines.length} بند إنجاز بالمستخلص، وسيتم حساب الإجمالي تلقائياً.` : 'يمكنك إدخال إجمالي يدوي أو فتح WBS واختيار بنود الإنجاز.'}</p>{!claimLines.length && <Input placeholder="إجمالي الأعمال" type="number" value={claim.gross_amount} onChange={e => setClaim({ ...claim, gross_amount: e.target.value })} />}<div className="mt-3 grid gap-3 md:grid-cols-2"><Input placeholder="خصم دفعة مقدمة" type="number" value={claim.advance_deduction} onChange={e => setClaim({ ...claim, advance_deduction: e.target.value })} /><Input placeholder="احتجاز" type="number" value={claim.retention_amount} onChange={e => setClaim({ ...claim, retention_amount: e.target.value })} /></div><div className="mt-4 flex gap-2"><Button onClick={() => claimMutation.mutate(claimProjectId)} disabled={claimMutation.isPending || (!claim.gross_amount && !claimLines.length)}>إرسال للاعتماد</Button><Button variant="outline" onClick={() => setClaimProjectId(null)}>إلغاء</Button></div></CardContent></Card>}
    <Card className="bg-muted/20"><CardContent className="flex items-start gap-3 p-5 text-sm"><Link2 className="mt-0.5 text-primary" size={20} /><p>كل بند أعمال يحمل كمية وسعر وإنجازاً تراكمياً، والمستخلص يحسب قيمته من البنود المنفذة ويرتبط بالتكلفة والقيد والتحصيل.</p><TrendingUp className="ms-auto hidden text-emerald-600 md:block" /></CardContent></Card>
  </div></MainLayout>;
}
