import { useState } from 'react';
import MainLayout from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { HardHat, FileCheck2, Wallet, TrendingUp, ClipboardList, Link2, Plus, X } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '@/lib/api';
import { toast } from 'sonner';

const steps = ['العقد', 'WBS والميزانية', 'المشتريات والتكلفة', 'قياس الإنجاز', 'المستخلص', 'الاعتماد والتحصيل'];
const emptyProject = { name: '', customer_id: '', contract_number: '', start_date: '', planned_end_date: '', contract_value: '', budget_cost: '', retention_percent: '0', scope: '' };
type ApiError = { response?: { data?: { message?: string } } };
type ProjectRow = { id: number; project_code: string; name: string; status: string; contract_value?: number; actual_cost?: number; budget_cost?: number; customer?: { name?: string } };
export default function Projects() {
  const queryClient = useQueryClient();
  const [costProjectId, setCostProjectId] = useState<number | null>(null);
  const [claimProjectId, setClaimProjectId] = useState<number | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [project, setProject] = useState(emptyProject);
  const [cost, setCost] = useState({ cost_type: 'material', amount: '', debit_account_id: '', credit_account_id: '' });
  const [claim, setClaim] = useState({ gross_amount: '', advance_deduction: '0', retention_amount: '0' });
  const { data, isLoading } = useQuery({ queryKey: ['projects-dashboard'], queryFn: async () => (await api.get('/projects/dashboard')).data.data });
  const createMutation = useMutation({ mutationFn: () => api.post('/projects', { ...project, customer_id: project.customer_id ? Number(project.customer_id) : null, contract_value: Number(project.contract_value || 0), budget_cost: Number(project.budget_cost || 0), retention_percent: Number(project.retention_percent || 0) }), onSuccess: () => { toast.success('تم إنشاء المشروع'); setProject(emptyProject); setShowCreate(false); queryClient.invalidateQueries({ queryKey: ['projects-dashboard'] }); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر إنشاء المشروع') });
  const costMutation = useMutation({ mutationFn: (id: number) => api.post(`/projects/${id}/costs`, { ...cost, amount: Number(cost.amount), debit_account_id: Number(cost.debit_account_id), credit_account_id: Number(cost.credit_account_id) }), onSuccess: () => { toast.success('تم تسجيل تكلفة المشروع وترحيل القيد'); setCostProjectId(null); queryClient.invalidateQueries({ queryKey: ['projects-dashboard'] }); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر تسجيل التكلفة') });
  const claimMutation = useMutation({ mutationFn: (id: number) => api.post(`/projects/${id}/claims`, { ...claim, gross_amount: Number(claim.gross_amount), advance_deduction: Number(claim.advance_deduction), retention_amount: Number(claim.retention_amount) }), onSuccess: () => { toast.success('تم إنشاء المستخلص وإرساله للاعتماد'); setClaimProjectId(null); queryClient.invalidateQueries({ queryKey: ['projects-dashboard'] }); }, onError: (e: ApiError) => toast.error(e.response?.data?.message || 'تعذر إنشاء المستخلص') });
  const projects = data?.projects?.data || [];
  return <MainLayout><div className="space-y-6" dir="rtl">
    <div className="rounded-2xl bg-gradient-to-l from-[#101a3b] to-[#c2410c] p-6 text-white"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><HardHat size={32} /><div><h1 className="text-2xl font-extrabold">المقاولات والمشروعات</h1><p className="text-orange-100">ربط العقد والتكلفة والإنجاز بالمستخلص والربحية والتحصيل.</p></div></div><Button onClick={() => setShowCreate(v => !v)} className="bg-white text-orange-800 hover:bg-orange-50"><Plus size={16} /> مشروع جديد</Button></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-5">{[['مشروعات نشطة', data?.active_count || 0], ['قيمة العقود', data?.contract_value || 0], ['الميزانية', data?.budget_cost || 0], ['التكلفة الفعلية', data?.actual_cost || 0], ['مستخلصات معلقة', data?.pending_claims || 0]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-white/10 p-3"><p className="text-xs text-orange-100">{label}</p><p className="text-xl font-bold">{value}</p></div>)}</div></div>
    {showCreate && <Card><CardHeader><CardTitle className="flex items-center justify-between">إنشاء مشروع جديد <Button variant="ghost" size="icon" onClick={() => setShowCreate(false)}><X size={16} /></Button></CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><Input placeholder="اسم المشروع" value={project.name} onChange={e => setProject({ ...project, name: e.target.value })} /><Input placeholder="Customer ID اختياري" type="number" value={project.customer_id} onChange={e => setProject({ ...project, customer_id: e.target.value })} /><Input placeholder="رقم العقد" value={project.contract_number} onChange={e => setProject({ ...project, contract_number: e.target.value })} /><Input placeholder="قيمة العقد" type="number" value={project.contract_value} onChange={e => setProject({ ...project, contract_value: e.target.value })} /></div><div className="mt-3 grid gap-3 md:grid-cols-4"><Input type="date" value={project.start_date} onChange={e => setProject({ ...project, start_date: e.target.value })} /><Input type="date" value={project.planned_end_date} onChange={e => setProject({ ...project, planned_end_date: e.target.value })} /><Input placeholder="الميزانية" type="number" value={project.budget_cost} onChange={e => setProject({ ...project, budget_cost: e.target.value })} /><Input placeholder="نسبة الاحتجاز" type="number" value={project.retention_percent} onChange={e => setProject({ ...project, retention_percent: e.target.value })} /></div><Button className="mt-4" onClick={() => createMutation.mutate()} disabled={createMutation.isPending || !project.name}>حفظ المشروع</Button></CardContent></Card>}
    <Card><CardHeader><CardTitle>دورة المشروع المترابطة</CardTitle></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-6">{steps.map((step, index) => <div key={step} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary text-primary-foreground">{index + 1}</span>{step}</div>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle>المشروعات</CardTitle></CardHeader><CardContent>{isLoading ? <p>جاري التحميل...</p> : projects.length === 0 ? <p className="py-8 text-center text-muted-foreground">لا توجد مشروعات حتى الآن</p> : <div className="space-y-3">{projects.map((item: ProjectRow) => <div key={item.id} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1.2fr_1fr_1fr_auto_auto] md:items-center"><div><p className="font-bold">{item.project_code} · {item.name}</p><p className="text-sm text-muted-foreground">العميل: {item.customer?.name || '-'}</p></div><div><Badge>{item.status}</Badge><p className="mt-2 text-xs text-muted-foreground">عقد: {item.contract_value || 0}</p></div><div><p className="text-sm">التكلفة: {item.actual_cost || 0}</p><p className="text-xs text-muted-foreground">الميزانية: {item.budget_cost || 0}</p></div><Button size="sm" variant="secondary" onClick={() => setCostProjectId(item.id)}><Wallet size={15} /> تكلفة</Button><Button size="sm" onClick={() => setClaimProjectId(item.id)}><FileCheck2 size={15} /> مستخلص</Button></div>)}</div>}</CardContent></Card>
    {costProjectId && <Card className="border-primary"><CardHeader><CardTitle><ClipboardList size={20} className="inline me-2" /> تسجيل تكلفة للمشروع #{costProjectId}</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><Input placeholder="نوع التكلفة" value={cost.cost_type} onChange={e => setCost({ ...cost, cost_type: e.target.value })} /><Input placeholder="القيمة" type="number" value={cost.amount} onChange={e => setCost({ ...cost, amount: e.target.value })} /><Input placeholder="الحساب المدين ID" type="number" value={cost.debit_account_id} onChange={e => setCost({ ...cost, debit_account_id: e.target.value })} /><Input placeholder="الحساب الدائن ID" type="number" value={cost.credit_account_id} onChange={e => setCost({ ...cost, credit_account_id: e.target.value })} /></div><div className="mt-4 flex gap-2"><Button onClick={() => costMutation.mutate(costProjectId)} disabled={costMutation.isPending || !cost.amount}>حفظ وترحيل التكلفة</Button><Button variant="outline" onClick={() => setCostProjectId(null)}>إلغاء</Button></div></CardContent></Card>}
    {claimProjectId && <Card className="border-orange-500"><CardHeader><CardTitle className="flex items-center gap-2"><FileCheck2 size={20} /> إنشاء مستخلص للمشروع #{claimProjectId}</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-3"><Input placeholder="إجمالي الأعمال" type="number" value={claim.gross_amount} onChange={e => setClaim({ ...claim, gross_amount: e.target.value })} /><Input placeholder="خصم دفعة مقدمة" type="number" value={claim.advance_deduction} onChange={e => setClaim({ ...claim, advance_deduction: e.target.value })} /><Input placeholder="احتجاز" type="number" value={claim.retention_amount} onChange={e => setClaim({ ...claim, retention_amount: e.target.value })} /></div><div className="mt-4 flex gap-2"><Button onClick={() => claimMutation.mutate(claimProjectId)} disabled={claimMutation.isPending || !claim.gross_amount}>إرسال للاعتماد</Button><Button variant="outline" onClick={() => setClaimProjectId(null)}>إلغاء</Button></div></CardContent></Card>}
    <Card className="bg-muted/20"><CardContent className="flex items-start gap-3 p-5 text-sm"><Link2 className="mt-0.5 text-primary" size={20} /><p>كل تكلفة تضاف للمشروع تُنشئ قيداً يومياً وتُحدّث التكلفة الفعلية، والمستخلص ينشئ ذمة مدينة ثم يتحول إلى إيراد محصل عند التحصيل.</p><TrendingUp className="ms-auto hidden text-emerald-600 md:block" /></CardContent></Card>
  </div></MainLayout>;
}
