import { useEffect, useState } from 'react';
import { Navigate } from 'react-router-dom';
import { ShieldCheck, Building2, Users, ToggleLeft, RefreshCw, Package, LogIn, Activity, BarChart3, UserCog, ChevronDown } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import api from '@/lib/api';
import MainLayout from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';

type Tenant={id:number;name:string;slug:string;status:string;plan:string;admins_count:number;products_count?:number;subscription_status?:string;trial_ends_at?:string};
type Module={module_key:string;is_enabled:boolean};
type Trial={id:number;name:string;trial_ends_at:string;days_remaining:number;subscription_status:string};
type Overview={stats:Record<string,number>;recent:Array<{id:number;description:string;actor_name:string;subject_type:string;created_at:string}>;tenants:Tenant[]};
const labels:Record<string,string>={crm:'CRM',email:'Email',whatsapp:'WhatsApp',google_calendar:'Google Calendar',google_drive:'Google Drive',tasks:'Tasks & Reminders',inventory:'Inventory',manufacturing:'Manufacturing',sales:'Sales',purchasing:'Purchasing',finance:'Finance',hr:'HR',pos:'POS',reports:'Reports',projects:'Projects',workflow:'Workflow',settings:'Settings',dashboard:'Dashboard',industries:'Industries',manufacturing_setup:'Manufacturing Setup',product_ledger:'Product Ledger'};
const statLabels:Record<string,string>={tenants:'كل العملاء',active_tenants:'عملاء نشطون',trial_tenants:'تجارب مجانية',admins:'مديرو العملاء',users:'المستخدمون',employees:'الموظفون',products:'المنتجات',sales_invoices:'فواتير المبيعات',activities_30d:'نشاط آخر 30 يومًا',logins_30d:'دخول آخر 30 يومًا'};

export default function SuperAdmin(){
 const {user}=useAuth(); const [tab,setTab]=useState<'overview'|'tenants'|'trials'|'modules'>('overview'); const [overview,setOverview]=useState<Overview|null>(null); const [tenants,setTenants]=useState<Tenant[]>([]); const [selected,setSelected]=useState<Tenant|null>(null); const [modules,setModules]=useState<Module[]>([]); const [trials,setTrials]=useState<Trial[]>([]); const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [o,t,tr]=await Promise.all([api.get('/super-admin/overview'),api.get('/super-admin/tenants'),api.get('/super-admin/trials')]);setOverview(o.data.data);setTenants(t.data.data??[]);setTrials(tr.data.data??[])}catch{toast.error('تعذر تحميل لوحة الإدارة')}finally{setLoading(false)}};
 const loadModules=async(t:Tenant)=>{setSelected(t);setTab('modules');try{const r=await api.get(`/super-admin/tenants/${t.id}/modules`);setModules(r.data.data??[])}catch{toast.error('تعذر تحميل الموديولات')}};
 useEffect(()=>{if(user?.super_admin)load()},[user?.super_admin]);
 const trialAction=async(id:number,action:'extend'|'activate'|'suspend')=>{try{const days=action==='extend'?Number(window.prompt('عدد الأيام الإضافية؟','7')):undefined;if(action==='extend'&&(!days||days<1))return;await api.post(`/super-admin/trials/${id}/${action}`,action==='extend'?{days}:{});toast.success('تم تحديث التجربة');load()}catch{toast.error('تعذر تحديث حالة التجربة')}};
 const toggle=async(m:Module)=>{if(!selected)return;const next=!m.is_enabled;setModules(xs=>xs.map(x=>x.module_key===m.module_key?{...x,is_enabled:next}:x));try{await api.patch(`/super-admin/tenants/${selected.id}/modules/${m.module_key}`,{is_enabled:next});toast.success('تم تحديث الموديول')}catch{setModules(xs=>xs.map(x=>x.module_key===m.module_key?{...x,is_enabled:!next}:x));toast.error('فشل تحديث الموديول')}};
 const createTenant=async()=>{const name=window.prompt('اسم الشركة؟','شركة جديدة')?.trim();if(!name)return;const slug=window.prompt('الرابط المختصر؟',name.toLowerCase().replace(/\s+/g,'-'))?.trim();if(!slug)return;const adminEmail=window.prompt('إيميل مدير الشركة (اختياري)؟')?.trim();const adminPassword=adminEmail?window.prompt('كلمة مرور مدير الشركة (8 أحرف على الأقل)؟')?.trim():undefined;if(adminEmail&&!adminPassword)return;try{await api.post('/super-admin/tenants',{name,slug,admin_email:adminEmail||undefined,admin_password:adminPassword||undefined});toast.success('تم إنشاء الشركة وربط بياناتها تلقائياً');load()}catch(error:any){toast.error(error.response?.data?.message||'تعذر إنشاء الشركة')}};
 if(!user)return null;if(!user.super_admin)return <Navigate to="/" replace/>;
 return <MainLayout><div className="space-y-6" dir="rtl">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ShieldCheck className="text-primary"/> مركز تحكم Super Admin</h1><p className="text-muted-foreground">تحكم كامل في العملاء، الموديولات، المستخدمين، المنتجات، الدخولات والنشاطات.</p></div><Button variant="outline" onClick={load}><RefreshCw className="ml-2 h-4 w-4"/> تحديث البيانات</Button></div>
  <div className="flex flex-wrap gap-2 border-b pb-3"><Button variant={tab==='overview'?'default':'ghost'} onClick={()=>setTab('overview')}><BarChart3 className="ml-2 h-4 w-4"/>نظرة عامة</Button><Button variant={tab==='tenants'?'default':'ghost'} onClick={()=>setTab('tenants')}><Building2 className="ml-2 h-4 w-4"/>العملاء</Button><Button variant={tab==='trials'?'default':'ghost'} onClick={()=>setTab('trials')}><Activity className="ml-2 h-4 w-4"/>التجارب</Button>{selected&&<Button variant={tab==='modules'?'default':'ghost'} onClick={()=>setTab('modules')}><ToggleLeft className="ml-2 h-4 w-4"/>موديولات {selected.name}</Button>}</div>
  {loading?<Card><CardContent className="py-16 text-center">جاري تحميل مركز الإدارة...</CardContent></Card>:tab==='overview'&&overview&&<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(overview.stats).map(([key,value])=><Card key={key}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{statLabels[key]??key}</p><p className="mt-2 text-3xl font-black">{value.toLocaleString('ar-EG')}</p></CardContent></Card>)}</div><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><LogIn className="h-5 w-5"/>آخر النشاطات والدخولات</CardTitle></CardHeader><CardContent className="space-y-3">{overview.recent.map(a=><div key={a.id} className="flex items-center justify-between border-b pb-3 text-sm"><div><p className="font-medium">{a.actor_name} · {a.description}</p><p className="text-xs text-muted-foreground">{a.subject_type?.split('\\').pop()} #{a.subject_id}</p></div><span className="text-xs text-muted-foreground">{new Date(a.created_at).toLocaleString('ar-EG')}</span></div>)}{!overview.recent.length&&<p className="text-muted-foreground">لا توجد نشاطات مسجلة.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Package className="h-5 w-5"/>ملخص العملاء والمنتجات</CardTitle></CardHeader><CardContent className="space-y-3">{overview.tenants.slice(0,8).map(t=><div key={t.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-semibold">{t.name}</p><p className="text-xs text-muted-foreground">{t.slug} · {t.admins_count} مستخدم · {t.products_count??0} منتج</p></div><Badge>{t.status}</Badge></div>)}</CardContent></Card></div></>}
  {tab==='tenants'&&<Card><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>كل العملاء ومساحات العمل ({tenants.length})</CardTitle><Button size="sm" onClick={createTenant}><Building2 className="ml-2 h-4 w-4"/>إنشاء شركة</Button></div></CardHeader><CardContent className="space-y-3">{tenants.map(t=><div key={t.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-semibold">{t.name}</p><p className="text-xs text-muted-foreground">https://{t.slug}.example.com · {t.admins_count} مستخدم · {t.products_count??0} منتج · الخطة {t.plan}</p></div><div className="flex items-center gap-2"><Badge>{t.status}</Badge><Button size="sm" variant="outline" onClick={()=>loadModules(t)}>إدارة الموديولات <ChevronDown className="mr-1 h-4 w-4"/></Button></div></div>)}</CardContent></Card>}
  {tab==='modules'&&selected&&<Card><CardHeader><CardTitle>الموديولات الظاهرة للعميل: {selected.name}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{modules.map(m=><div key={m.module_key} className="flex items-center justify-between rounded-lg border p-3"><span>{labels[m.module_key]??m.module_key}</span><Switch checked={m.is_enabled} onCheckedChange={()=>toggle(m)} aria-label={`تفعيل ${m.module_key}`}/></div>)}</CardContent></Card>}
  {tab==='trials'&&<Card><CardHeader><CardTitle>إدارة التجارب المجانية ({trials.length})</CardTitle></CardHeader><CardContent className="space-y-3">{trials.map(t=><div key={t.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-semibold">{t.name}</p><p className="text-xs text-muted-foreground">تنتهي {new Date(t.trial_ends_at).toLocaleDateString('ar-EG')} · متبقي {t.days_remaining} يوم</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>trialAction(t.id,'extend')}>تمديد</Button><Button size="sm" onClick={()=>trialAction(t.id,'activate')}>تفعيل</Button><Button size="sm" variant="destructive" onClick={()=>trialAction(t.id,'suspend')}>تعليق</Button></div></div>)}{!trials.length&&<p className="text-muted-foreground">لا توجد تجارب حالية.</p>}</CardContent></Card>}
 </div></MainLayout>
}
