import MainLayout from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Activity, CheckCircle2, Database, FileText, Link2, RefreshCw, Wallet } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import api from '@/lib/api';

export default function Workflow() {
  const { data, isLoading, refetch } = useQuery({ queryKey: ['workflow-transactions'], queryFn: async () => (await api.get('/workflow/transactions?per_page=40')).data });
  const events = data?.data?.data || [];
  const summary = data?.summary || {};
  return <MainLayout><div className="space-y-6" dir="rtl"><div className="rounded-2xl bg-gradient-to-l from-[#101a3b] via-[#172554] to-[#0891b2] p-6 text-white"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Activity size={32} /><div><h1 className="text-2xl font-extrabold">مركز ترابط العمليات</h1><p className="text-cyan-100">كل معاملة لها أثر قابل للتتبع في المخزون والمالية وسجل النشاط.</p></div></div><button onClick={() => refetch()} className="rounded-lg bg-white/10 p-3 hover:bg-white/20"><RefreshCw size={19} /></button></div></div><div className="grid gap-4 sm:grid-cols-4">{[['إجمالي الأحداث', summary.total || 0, Activity], ['مكتملة', summary.completed || 0, CheckCircle2], ['فاشلة', summary.failed || 0, FileText], ['اليوم', summary.today || 0, Link2]].map(([label, value, Icon]) => <Card key={String(label)}><CardContent className="flex items-center gap-3 p-5"><Icon className="text-primary" size={22} /><div><p className="text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="flex items-center gap-2"><Link2 className="text-primary" size={21} /> خط سير المعاملات</CardTitle></CardHeader><CardContent>{isLoading ? <p>جاري تحميل سجل التشغيل...</p> : <div className="space-y-3">{events.map((event: any) => <div key={event.event_key} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_1.1fr_0.7fr_0.9fr]"><div><p className="font-semibold">{event.event}</p><p className="text-xs text-muted-foreground">{event.source_type?.split('\\').pop()} #{event.source_id}</p></div><div className="flex items-center gap-2 text-sm"><Database size={16} className="text-cyan-600" />{event.inventory_movement_id ? 'حركة مخزون مرتبطة' : 'بدون حركة مخزون'}<Wallet size={16} className="ms-2 text-violet-600" />{event.journal_entry_id ? 'قيد مرتبط' : 'بدون قيد'}</div><Badge variant={event.status === 'completed' ? 'default' : 'destructive'}>{event.status}</Badge><p className="text-xs text-muted-foreground">{event.occurred_at ? new Date(event.occurred_at).toLocaleString('ar-EG') : '-'}</p></div>)}</div>}</CardContent></Card></div></MainLayout>;
}
