import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Wallet, Users, Receipt, Plus, Eye, ArrowUpRight, ArrowDownRight } from 'lucide-react';
import MainLayout from '@/components/layout/MainLayout';
import { useLanguage } from '@/contexts/LanguageContext';
import api from '@/lib/api';

type Employee = { id:number; name:string; name_ar?:string; employee_code?:string; salary:number };
type Treasury = { id:number; name:string; balance:number; currency?:string };
 type Payroll = { id:number; employee:Employee; period_start:string; period_end:string; base_salary:number; allowances:number; deductions:number; advance_deductions:number; net_salary:number; due_date?:string; status:string; paid_at?:string; notes?:string; adjustments?:Record<string, unknown> };
type Advance = { id:number; employee:Employee; amount:number; paid_amount:number; remaining_amount:number; advance_date:string; reason:string; status:string; recorded_by_name?:string; last_payment_at?:string; payments?:Array<{id:number;amount:number;payment_date:string;notes?:string;source_payroll_id?:number|null;treasury?:Treasury|null}> };
type Bonus = { id:number; employee:Employee; bonus_date:string; amount:number; reason:string; status:string; treasury?:Treasury; paid_at?:string; journal_entry_id?:number; finance_id?:number };
type Report = { employees:Employee[]; treasuries:Treasury[]; payrolls:Payroll[]; advances:Advance[]; bonuses:Bonus[]; summary:Record<string,number> };
type Statement = { employee:Employee; summary:Record<string,number>; transactions:Array<{date:string;type:string;reason:string;amount:number;direction:string;balance_after:number;notes?:string}> };
const money=(v:number)=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})+' ج.م';
const statusLabel=(s:string, ar:boolean)=>({due:ar?'مستحق':'Due',paid:ar?'تم الدفع':'Paid',overdue:ar?'متأخر':'Overdue',new:ar?'جديدة':'New',repaying:ar?'قيد السداد':'Repaying'}[s]||s);

export default function EmployeeFinancialReports(){
 const {language}=useLanguage(); const ar=language==='ar'; const qc=useQueryClient();
 const [employeeId,setEmployeeId]=useState('all'); const [reportFrom,setReportFrom]=useState(new Date().toISOString().slice(0,10)); const [reportTo,setReportTo]=useState(new Date().toISOString().slice(0,10)); const [bonusOpen,setBonusOpen]=useState(false); const [collectBonus,setCollectBonus]=useState<Bonus|null>(null); const [statement,setStatement]=useState<Statement|null>(null); const [advanceOpen,setAdvanceOpen]=useState(false); const [payrollOpen,setPayrollOpen]=useState(false); const [paymentAdvance,setPaymentAdvance]=useState<Advance|null>(null);
 const [bonusForm,setBonusForm]=useState({employee_id:'',bonus_date:new Date().toISOString().slice(0,10),amount:'',reason:'',notes:''});
 const [advanceForm,setAdvanceForm]=useState({employee_id:'',treasury_id:'',amount:'',advance_date:new Date().toISOString().slice(0,10),reason:'',notes:''});
 const [payrollForm,setPayrollForm]=useState({employee_id:'',treasury_id:'',period_start:'',period_end:'',base_salary:'',allowances:'0',deductions:'0',advance_deductions:'0',due_date:'',status:'due',notes:''}); const [paymentForm,setPaymentForm]=useState({treasury_id:'',amount:'',payment_date:new Date().toISOString().slice(0,10),notes:''});
 const query=useQuery<Report>({queryKey:['employee-financial-reports',employeeId,reportFrom,reportTo],queryFn:async()=>{const params:any={from:reportFrom,to:reportTo};if(employeeId!=='all')params.employee_id=employeeId;const r=await api.get('/employee-financial-reports', {params});const report=r.data.data;return {...report,payrolls:report.payrolls.map((payroll:Payroll)=>({...payroll,period_start:payroll.period_start.slice(0,10),period_end:payroll.period_end.slice(0,10)}))};}});
 const treasuryQuery=useQuery<Treasury[]>({queryKey:['employee-report-treasuries'],queryFn:async()=>{const r=await api.post('/treasury/index',{filters:{},orderBy:'name',orderByDirection:'asc',perPage:100,paginate:false});return r.data.data||[];}});
 const data=query.data;
 const treasuries=treasuryQuery.data||data?.treasuries||[];
 const saveBonus=useMutation({mutationFn:()=>api.post('/employee-financial-reports/bonuses',{...bonusForm,employee_id:Number(bonusForm.employee_id),amount:Number(bonusForm.amount)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['employee-financial-reports']});setBonusOpen(false);setBonusForm({...bonusForm,employee_id:'',amount:'',reason:'',notes:''});}});
 const saveBonusCollection=useMutation({mutationFn:()=>api.post(`/employee-financial-reports/bonuses/${collectBonus!.id}/collect`,{treasury_id:Number((collectBonus as any).selectedTreasuryId),paid_at:new Date().toISOString().slice(0,10)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['employee-financial-reports']});setCollectBonus(null);}});
 const saveAdvance=useMutation({mutationFn:()=>api.post('/employee-financial-reports/advances',{...advanceForm,employee_id:Number(advanceForm.employee_id),treasury_id:Number(advanceForm.treasury_id),amount:Number(advanceForm.amount)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['employee-financial-reports']});setAdvanceOpen(false);setAdvanceForm({...advanceForm,employee_id:'',treasury_id:'',amount:'',reason:'',notes:''});}});
 const savePayroll=useMutation({mutationFn:()=>api.post('/employee-financial-reports/payrolls',{...payrollForm,employee_id:Number(payrollForm.employee_id),treasury_id:payrollForm.treasury_id?Number(payrollForm.treasury_id):null,base_salary:Number(payrollForm.base_salary),allowances:Number(payrollForm.allowances),deductions:Number(payrollForm.deductions),advance_deductions:Number(payrollForm.advance_deductions)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['employee-financial-reports']});setPayrollOpen(false);}});
 const savePayment=useMutation({mutationFn:()=>api.post(`/employee-financial-reports/advances/${paymentAdvance!.id}/payments`,{...paymentForm,treasury_id:Number(paymentForm.treasury_id),amount:Number(paymentForm.amount)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['employee-financial-reports']});setPaymentAdvance(null);setPaymentForm({treasury_id:'',amount:'',payment_date:new Date().toISOString().slice(0,10),notes:''});}});
 const loadStatement=async(e:Employee)=>setStatement((await api.get(`/employee-financial-reports/${e.id}/statement`)).data.data);
 const employees=data?.employees||[];
 return <MainLayout activeItem="employee-financial-reports"><div className="p-4 md:p-6 space-y-6" dir={ar?'rtl':'ltr'}>
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{ar?'التقارير المالية للموظفين':'Employee Financial Reports'}</h1><p className="text-muted-foreground">{ar?'متابعة الرواتب والسلف والمبالغ المستحقة وكشف الحساب الزمني':'Track payroll, advances, outstanding balances and chronological statements'}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setBonusOpen(true)}><Plus className="me-2 h-4 w-4"/>{ar?'تسجيل بونص':'Record bonus'}</Button><Button variant="outline" onClick={()=>setPayrollOpen(true)}><Plus className="me-2 h-4 w-4"/>{ar?'تسجيل راتب':'Record payroll'}</Button><Button onClick={()=>setAdvanceOpen(true)}><Plus className="me-2 h-4 w-4"/>{ar?'تسجيل سلفة':'Record advance'}</Button></div></div>
  <div className="flex flex-wrap items-center gap-3"><Label>{ar?'من يوم':'From'} </Label><Input type="date" value={reportFrom} onChange={e=>setReportFrom(e.target.value)}/><Label>{ar?'إلى يوم':'To'} </Label><Input type="date" value={reportTo} onChange={e=>setReportTo(e.target.value)}/><Label>{ar?'الموظف':'Employee'}</Label><Select value={employeeId} onValueChange={setEmployeeId}><SelectTrigger className="w-64"><SelectValue placeholder={ar?'كل الموظفين':'All employees'}/></SelectTrigger><SelectContent><SelectItem value="all">{ar?'كل الموظفين':'All employees'}</SelectItem>{employees.map(e=><SelectItem key={e.id} value={String(e.id)}>{e.name}</SelectItem>)}</SelectContent></Select></div>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[[Wallet,ar?'إجمالي الرواتب':'Total payrolls','total_payrolls'],[ArrowDownRight,ar?'إجمالي السلف':'Total advances','total_advances'],[ArrowUpRight,ar?'المسدّد من السلف':'Advance paid','total_advance_paid'],[Receipt,ar?'المتبقي على الموظفين':'Outstanding advances','remaining_advances'],[Users,ar?'رواتب مستحقة':'Due payrolls','due_payrolls']].map(([Icon,label,key])=><Card key={String(key)}><CardContent className="p-4"><div className="flex gap-2 text-sm text-muted-foreground"><Icon className="h-4 w-4"/>{label}</div><div className="text-xl font-bold mt-2">{key==='due_payrolls'?data?.summary?.[String(key)]||0:money(data?.summary?.[String(key)]||0)}</div></CardContent></Card>)}</div>
  <Tabs defaultValue="payrolls"><TabsList><TabsTrigger value="payrolls">{ar?'تقرير الرواتب':'Payroll report'}</TabsTrigger><TabsTrigger value="bonuses">{ar?'البونص اليومي':'Daily bonuses'}</TabsTrigger><TabsTrigger value="advances">{ar?'تقرير السلف':'Advances report'}</TabsTrigger></TabsList>
   <TabsContent value="payrolls"><Card><CardHeader><CardTitle>{ar?'رواتب الموظفين':'Employee payrolls'}</CardTitle></CardHeader><CardContent className="overflow-auto"><Table><TableHeader><TableRow>{[ar?'الموظف':'Employee',ar?'الفترة':'Period',ar?'الأساسي':'Base',ar?'البدلات':'Allowances',ar?'الخصومات':'Deductions',ar?'خصم السلف':'Advance deduction',ar?'الصافي':'Net',ar?'الاستحقاق':'Due date',ar?'الحالة':'Status',ar?'الصرف':'Paid at',ar?'تفاصيل التعديل':'Adjustments'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{data?.payrolls.map(p=><TableRow key={p.id}><TableCell className="font-medium">{p.employee?.name}</TableCell><TableCell>{p.period_start} — {p.period_end}</TableCell><TableCell>{money(p.base_salary)}</TableCell><TableCell>{money(p.allowances)}</TableCell><TableCell>{money(p.deductions)}</TableCell><TableCell>{money(p.advance_deductions)}</TableCell><TableCell className="font-bold">{money(p.net_salary)}</TableCell><TableCell>{p.due_date||'-'}</TableCell><TableCell><Badge variant={p.status==='paid'?'default':p.status==='overdue'?'destructive':'secondary'}>{statusLabel(p.status,ar)}</Badge></TableCell><TableCell>{p.paid_at||'-'}</TableCell><TableCell>{p.adjustments ? JSON.stringify(p.adjustments) : p.notes||'-'}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
   <TabsContent value="bonuses"><Card><CardHeader><CardTitle>{ar?'البونص اليومي':'Daily employee bonuses'}</CardTitle></CardHeader><CardContent className="overflow-auto"><Table><TableHeader><TableRow>{[ar?'الموظف':'Employee',ar?'التاريخ':'Date',ar?'القيمة':'Amount',ar?'السبب':'Reason',ar?'الحالة':'Status',ar?'الخزينة':'Treasury',ar?'القيد':'Journal',ar?'الإجراء':'Action'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{data?.bonuses?.map(b=><TableRow key={b.id}><TableCell>{b.employee?.name}</TableCell><TableCell>{b.bonus_date}</TableCell><TableCell className="font-bold">{money(b.amount)}</TableCell><TableCell>{b.reason}</TableCell><TableCell><Badge variant={b.status==='paid'?'default':'secondary'}>{b.status==='paid'?(ar?'تم التحصيل':'Paid'):(ar?'مستحق':'Due')}</Badge></TableCell><TableCell>{b.treasury?.name||'-'}</TableCell><TableCell>{b.journal_entry_id||'-'}</TableCell><TableCell><Button size="sm" disabled={b.status==='paid'} onClick={()=>setCollectBonus(b)}>{ar?'تحصيل من الخزينة':'Collect'}</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
   <TabsContent value="advances"><Card><CardHeader><CardTitle>{ar?'سلف الموظفين':'Employee advances'}</CardTitle></CardHeader><CardContent className="overflow-auto"><Table><TableHeader><TableRow>{[ar?'الموظف':'Employee',ar?'القيمة':'Amount',ar?'التاريخ':'Date',ar?'السبب':'Reason',ar?'المسجل بواسطة':'Recorded by',ar?'المسدّد':'Paid',ar?'المتبقي':'Remaining',ar?'آخر سداد':'Last payment',ar?'سجل الدفعات':'Payment history',ar?'الحالة':'Status',ar?'السداد':'Repay',ar?'كشف الحساب':'Statement'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{data?.advances.map(a=><TableRow key={a.id}><TableCell className="font-medium">{a.employee?.name}</TableCell><TableCell>{money(a.amount)}</TableCell><TableCell>{a.advance_date}</TableCell><TableCell>{a.reason}</TableCell><TableCell>{a.recorded_by_name||'-'}</TableCell><TableCell>{money(a.paid_amount)}</TableCell><TableCell className="font-bold">{money(a.remaining_amount)}</TableCell><TableCell>{a.last_payment_at||'-'}</TableCell><TableCell className="min-w-48">{a.payments?.length ? a.payments.map(p=><div key={p.id} className="text-xs">{money(p.amount)} · {p.payment_date}{p.source_payroll_id ? ` · ${ar?'خصم راتب':'Payroll deduction'}` : ''}</div>) : '-'}</TableCell><TableCell><Badge variant={a.status==='paid'?'default':'secondary'}>{statusLabel(a.status,ar)}</Badge></TableCell><TableCell><Button size="sm" variant="outline" disabled={!a.remaining_amount} onClick={()=>setPaymentAdvance(a)}>{ar?'تسجيل دفعة':'Add payment'}</Button></TableCell><TableCell><Button size="sm" variant="ghost" onClick={()=>loadStatement(a.employee)}><Eye className="h-4 w-4 me-1"/>{ar?'عرض':'View'}</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
  </Tabs>
  <Dialog open={!!statement} onOpenChange={open=>!open&&setStatement(null)}><DialogContent className="max-w-5xl max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{ar?'كشف حساب الموظف: ':'Employee statement: '}{statement?.employee.name}</DialogTitle></DialogHeader>{statement&&<><div className="grid grid-cols-3 gap-3 mb-4">{[['salary_total',ar?'إجمالي الرواتب':'Payroll'],['advances_remaining',ar?'المتبقي من السلف':'Advances remaining'],['balance',ar?'الرصيد بعد الحركة':'Balance']].map(([k,l])=><Card key={String(k)}><CardContent className="p-3"><p className="text-sm text-muted-foreground">{l}</p><p className="font-bold">{money(statement.summary[String(k)]||0)}</p></CardContent></Card>)}</div><Table><TableHeader><TableRow>{[ar?'التاريخ':'Date',ar?'نوع الحركة':'Type',ar?'السبب':'Reason',ar?'المبلغ':'Amount',ar?'الرصيد بعد الحركة':'Balance after',ar?'ملاحظات':'Notes'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{statement.transactions.map((t,i)=><TableRow key={`${t.reference_id}-${i}`}><TableCell>{t.date}</TableCell><TableCell>{t.type}</TableCell><TableCell>{t.reason}</TableCell><TableCell className={t.direction==='debit'?'text-destructive':'text-emerald-600'}>{t.direction==='debit'?'-':'+'}{money(t.amount)}</TableCell><TableCell>{money(t.balance_after)}</TableCell><TableCell>{t.notes||'-'}</TableCell></TableRow>)}</TableBody></Table></>}</DialogContent></Dialog>
  <Dialog open={bonusOpen} onOpenChange={setBonusOpen}><DialogContent><DialogHeader><DialogTitle>{ar?'تسجيل بونص موظف':'Record employee bonus'}</DialogTitle></DialogHeader><div className="grid gap-3"><Label>{ar?'الموظف':'Employee'}</Label><Select value={bonusForm.employee_id} onValueChange={v=>setBonusForm({...bonusForm,employee_id:v})}><SelectTrigger><SelectValue placeholder={ar?'اختر الموظف':'Select employee'}/></SelectTrigger><SelectContent>{employees.map(e=><SelectItem key={e.id} value={String(e.id)}>{e.name}</SelectItem>)}</SelectContent></Select><Label>{ar?'التاريخ':'Date'}</Label><Input type="date" value={bonusForm.bonus_date} onChange={e=>setBonusForm({...bonusForm,bonus_date:e.target.value})}/><Label>{ar?'المبلغ':'Amount'}</Label><Input type="number" value={bonusForm.amount} onChange={e=>setBonusForm({...bonusForm,amount:e.target.value})}/><Label>{ar?'السبب':'Reason'}</Label><Input value={bonusForm.reason} onChange={e=>setBonusForm({...bonusForm,reason:e.target.value})}/><Button disabled={!bonusForm.employee_id||!bonusForm.amount||!bonusForm.reason} onClick={()=>saveBonus.mutate()}>{ar?'حفظ البونص':'Save bonus'}</Button></div></DialogContent></Dialog>
  <Dialog open={!!collectBonus} onOpenChange={open=>!open&&setCollectBonus(null)}><DialogContent><DialogHeader><DialogTitle>{ar?'تحصيل البونص من الخزينة':'Collect bonus from treasury'}</DialogTitle></DialogHeader><div className="grid gap-3"><p>{collectBonus?.employee?.name} — {money(collectBonus?.amount||0)}</p><Select value={String((collectBonus as any)?.selectedTreasuryId||'')} onValueChange={v=>setCollectBonus(collectBonus?({...collectBonus,selectedTreasuryId:v} as any):null)}><SelectTrigger><SelectValue placeholder={ar?'اختر الخزينة':'Select treasury'}/></SelectTrigger><SelectContent>{treasuries.map(t=><SelectItem key={t.id} value={String(t.id)}>{t.name} — {money(t.balance)}</SelectItem>)}</SelectContent></Select><Button disabled={!((collectBonus as any)?.selectedTreasuryId)} onClick={()=>saveBonusCollection.mutate()}>{ar?'تم التحصيل':'Mark collected'}</Button></div></DialogContent></Dialog>
  <Dialog open={advanceOpen} onOpenChange={setAdvanceOpen}><DialogContent><DialogHeader><DialogTitle>{ar?'تسجيل سلفة موظف':'Record employee advance'}</DialogTitle></DialogHeader><div className="grid gap-3">{[[ar?'الموظف':'Employee','employee_id'],[ar?'الخزينة المصروف منها':'Source treasury','treasury_id'],[ar?'قيمة السلفة':'Amount','amount'],[ar?'التاريخ':'Date','advance_date'],[ar?'السبب':'Reason','reason'],[ar?'ملاحظات':'Notes','notes']].map(([l,k])=><div key={k}><Label>{l}</Label>{k==='employee_id'?<Select value={advanceForm.employee_id} onValueChange={v=>setAdvanceForm({...advanceForm,employee_id:v})}><SelectTrigger><SelectValue placeholder={ar?'اختر الموظف':'Select employee'}/></SelectTrigger><SelectContent>{employees.map(e=><SelectItem key={e.id} value={String(e.id)}>{e.name}</SelectItem>)}</SelectContent></Select>:k==='treasury_id'?<Select value={advanceForm.treasury_id} onValueChange={v=>setAdvanceForm({...advanceForm,treasury_id:v})}><SelectTrigger><SelectValue placeholder={ar?'اختر الخزينة':'Select treasury'}/></SelectTrigger><SelectContent>{treasuries.map(t=><SelectItem key={t.id} value={String(t.id)}>{t.name} — {money(t.balance)}</SelectItem>)}</SelectContent></Select>:<Input type={k.includes('date')?'date':k==='amount'?'number':'text'} value={(advanceForm as any)[k]} onChange={e=>setAdvanceForm({...advanceForm,[k]:e.target.value})}/>}</div>)}<Button disabled={!advanceForm.employee_id||!advanceForm.treasury_id||!advanceForm.amount||!advanceForm.reason||saveAdvance.isPending} onClick={()=>saveAdvance.mutate()}>{ar?'حفظ السلفة':'Save advance'}</Button></div></DialogContent></Dialog>
    <Dialog open={payrollOpen} onOpenChange={setPayrollOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{ar?'تسجيل راتب':'Record payroll'}</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-3">{[[ar?'الموظف':'Employee','employee_id'],[ar?'حالة الراتب':'Status','status'],[ar?'خزينة الصرف':'Payment treasury','treasury_id'],[ar?'بداية الفترة':'Period start','period_start'],[ar?'نهاية الفترة':'Period end','period_end'],[ar?'الراتب الأساسي':'Base salary','base_salary'],[ar?'البدلات':'Allowances','allowances'],[ar?'الخصومات':'Deductions','deductions'],[ar?'خصم السلف':'Advance deductions','advance_deductions'],[ar?'تاريخ الاستحقاق':'Due date','due_date']].map(([l,k])=><div key={k}><Label>{l}</Label>{k==='employee_id'?<Select value={payrollForm.employee_id} onValueChange={v=>setPayrollForm({...payrollForm,employee_id:v})}><SelectTrigger><SelectValue placeholder={ar?'اختر الموظف':'Select employee'}/></SelectTrigger><SelectContent>{employees.map(e=><SelectItem key={e.id} value={String(e.id)}>{e.name}</SelectItem>)}</SelectContent></Select>:k==='treasury_id'?<Select value={payrollForm.treasury_id} onValueChange={v=>setPayrollForm({...payrollForm,treasury_id:v})}><SelectTrigger><SelectValue placeholder={ar?'اختر خزينة الصرف':'Select payment treasury'}/></SelectTrigger><SelectContent>{treasuries.map(t=><SelectItem key={t.id} value={String(t.id)}>{t.name} — {money(t.balance)}</SelectItem>)}</SelectContent></Select>:k==='status'?<Select value={payrollForm.status} onValueChange={v=>setPayrollForm({...payrollForm,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="due">{ar?'مستحق فقط':'Due only'}</SelectItem><SelectItem value="paid">{ar?'تم الصرف الآن':'Paid now'}</SelectItem></SelectContent></Select>:<Input type={k.includes('date') || k === 'period_start' || k === 'period_end' ? 'date' : 'number'} value={(payrollForm as any)[k]} onChange={e=>setPayrollForm({...payrollForm,[k]:e.target.value})}/>}</div>)}<Button className="col-span-2" disabled={!payrollForm.employee_id||!payrollForm.period_start||!payrollForm.period_end||!payrollForm.base_salary||payrollForm.status==='paid'&&!payrollForm.treasury_id||savePayroll.isPending} onClick={()=>savePayroll.mutate()}>{ar?'حفظ الراتب':'Save payroll'}</Button></div></DialogContent></Dialog>
  <Dialog open={!!paymentAdvance} onOpenChange={open=>!open&&setPaymentAdvance(null)}><DialogContent><DialogHeader><DialogTitle>{ar?'تسجيل سداد سلفة':'Record advance repayment'}</DialogTitle></DialogHeader><div className="grid gap-3"><p className="text-sm text-muted-foreground">{paymentAdvance?.employee?.name} — {ar?'المتبقي':'Remaining'}: {money(paymentAdvance?.remaining_amount||0)}</p><div><Label>{ar?'خزينة التحصيل':'Receiving treasury'}</Label><Select value={paymentForm.treasury_id} onValueChange={v=>setPaymentForm({...paymentForm,treasury_id:v})}><SelectTrigger><SelectValue placeholder={ar?'اختر الخزينة':'Select treasury'}/></SelectTrigger><SelectContent>{treasuries.map(t=><SelectItem key={t.id} value={String(t.id)}>{t.name} — {money(t.balance)}</SelectItem>)}</SelectContent></Select></div><div><Label>{ar?'المبلغ':'Amount'}</Label><Input type="number" max={paymentAdvance?.remaining_amount} value={paymentForm.amount} onChange={e=>setPaymentForm({...paymentForm,amount:e.target.value})}/></div><div><Label>{ar?'تاريخ السداد':'Payment date'}</Label><Input type="date" value={paymentForm.payment_date} onChange={e=>setPaymentForm({...paymentForm,payment_date:e.target.value})}/></div><div><Label>{ar?'ملاحظات':'Notes'}</Label><Input value={paymentForm.notes} onChange={e=>setPaymentForm({...paymentForm,notes:e.target.value})}/></div><Button disabled={!paymentForm.treasury_id||!paymentForm.amount||savePayment.isPending} onClick={()=>savePayment.mutate()}>{ar?'حفظ السداد':'Save payment'}</Button></div></DialogContent></Dialog>
 </div></MainLayout>;
}
