import { useEffect, useMemo, useState } from 'react';
import api from '@/lib/api';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import { Plus, GripVertical, Activity, Target, TrendingUp } from 'lucide-react';
import { BarChart3, MailCheck, Percent, UsersRound } from 'lucide-react';

type Stage = { id: number; name: string; name_ar?: string; sort_order: number; deals_count?: number };
type Deal = { id: number; title: string; value: number; stage_id: number; customer?: { name: string }; lead?: { name: string }; expected_close_date?: string };
type Lead = { id: number; name: string; company?: string; status: string; phone?: string };
type Customer = { id: number; name: string; email?: string };
type EmailTemplate = { id: number; name: string; subject: string; body: string };
type EmailLog = { id: number; to_email: string; subject: string; status: string; created_at: string };
type Analytics = { summary: { leads: number; deals: number; pipeline_value: number; won_value: number; conversion_rate: number; win_rate: number; activities: number; emails_sent: number; email_success_rate: number }; funnel: { name: string; name_ar?: string; deals: number; value: number }[]; lead_sources: { source: string; leads: number; converted: number; conversion_rate: number }[]; activities_by_type: { type: string; count: number }[]; daily_trend: { date: string; leads: number; deals: number; activities: number; emails: number }[] };

export default function CrmPipeline() {
  const [stages, setStages] = useState<Stage[]>([]); const [deals, setDeals] = useState<Deal[]>([]); const [leads, setLeads] = useState<Lead[]>([]); const [tab, setTab] = useState<'pipeline'|'leads'|'activities'|'email'|'analytics'>('pipeline'); const [showLead, setShowLead] = useState(false); const [lead, setLead] = useState({ name: '', company: '', phone: '', email: '', source: 'website' }); const [activities, setActivities] = useState<any[]>([]); const [customers, setCustomers] = useState<Customer[]>([]); const [templates, setTemplates] = useState<EmailTemplate[]>([]); const [emailLogs, setEmailLogs] = useState<EmailLog[]>([]); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [email, setEmail] = useState({ customer_id: '', template_id: '', subject: '', body: '' });
  const load = async () => { try { const [s, d, l, a] = await Promise.all([api.get('/crm/pipeline-stages'), api.get('/crm/deals?per_page=100'), api.get('/crm/leads?per_page=100'), api.get('/crm/activities?per_page=20')]); setStages(s.data.data ?? []); setDeals(d.data.data?.data ?? d.data.data ?? []); setLeads(l.data.data?.data ?? l.data.data ?? []); setActivities(a.data.data?.data ?? a.data.data ?? []); } catch { toast.error('تعذر تحميل بيانات CRM'); } };
  useEffect(() => { load(); api.post('/customer/index', { paginate: false, perPage: 500 }).then(response => setCustomers(response.data.data ?? [])).catch(() => undefined); api.get('/crm/email/templates').then(response => setTemplates(response.data.data ?? [])).catch(() => undefined); api.get('/crm/email/logs?per_page=20').then(response => setEmailLogs(response.data.data?.data ?? response.data.data ?? [])).catch(() => undefined); }, []);
  const byStage = useMemo(() => stages.reduce<Record<number, Deal[]>>((all, stage) => { all[stage.id] = deals.filter(d => d.stage_id === stage.id); return all; }, {}), [stages, deals]);
  const move = async (deal: Deal, stageId: number) => { if (deal.stage_id === stageId) return; const old = deal.stage_id; setDeals(items => items.map(x => x.id === deal.id ? { ...x, stage_id: stageId } : x)); try { await api.post(`/crm/deals/${deal.id}/move-stage`, { stage_id: stageId }); } catch { setDeals(items => items.map(x => x.id === deal.id ? { ...x, stage_id: old } : x)); toast.error('تعذر نقل الصفقة'); } };
  const createLead = async () => { if (!lead.name.trim()) return; try { await api.post('/crm/leads', lead); setLead({ name:'', company:'', phone:'', email:'', source:'website' }); setShowLead(false); await load(); toast.success('تم إنشاء العميل المحتمل'); } catch { toast.error('تعذر إنشاء العميل المحتمل'); } };
  const sendEmail = async () => { if (!email.customer_id || !email.subject.trim() || !email.body.trim()) return toast.error('اختر العميل واكتب العنوان والمحتوى'); try { await api.post(`/crm/customers/${email.customer_id}/send-email`, { template_id: email.template_id || undefined, subject: email.subject, body: email.body }); setEmail({ customer_id:'', template_id:'', subject:'', body:'' }); await load(); toast.success('تم وضع البريد في قائمة الإرسال'); } catch { toast.error('تعذر جدولة البريد'); } };
  const useTemplate = (id: string) => { const item = templates.find(template => String(template.id) === id); setEmail({...email, template_id:id, subject:item?.subject ?? email.subject, body:item?.body ?? email.body}); };
  const loadAnalytics = async () => { try { const response = await api.get('/crm/reports/analytics'); setAnalytics(response.data.data); } catch { toast.error('تعذر تحميل التقارير'); } };
  return <div className="space-y-4" dir="rtl"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2"><Button variant={tab==='pipeline'?'default':'outline'} onClick={() => setTab('pipeline')}><Target className="ml-2 h-4 w-4"/>Pipeline</Button><Button variant={tab==='leads'?'default':'outline'} onClick={() => setTab('leads')}>Leads ({leads.length})</Button><Button variant={tab==='activities'?'default':'outline'} onClick={() => setTab('activities')}><Activity className="ml-2 h-4 w-4"/>Timeline</Button><Button variant={tab==='email'?'default':'outline'} onClick={() => setTab('email')}>Email</Button><Button variant={tab==='analytics'?'default':'outline'} onClick={() => { setTab('analytics'); loadAnalytics(); }}><BarChart3 className="ml-2 h-4 w-4"/>التقارير</Button></div><Button onClick={() => setShowLead(true)}><Plus className="ml-2 h-4 w-4"/>عميل محتمل</Button></div>
    {tab === 'pipeline' && <div className="grid gap-4 overflow-x-auto pb-3 md:grid-cols-3 xl:grid-cols-6">{stages.map(stage => <Card key={stage.id} className="min-w-[220px] bg-muted/30"><CardHeader className="pb-2"><CardTitle className="flex items-center justify-between text-sm"><span>{stage.name_ar || stage.name}</span><Badge variant="secondary">{byStage[stage.id]?.length ?? 0}</Badge></CardTitle></CardHeader><CardContent className="space-y-2" onDragOver={e => e.preventDefault()} onDrop={e => { const id = Number(e.dataTransfer.getData('deal')); const deal = deals.find(x => x.id === id); if (deal) move(deal, stage.id); }}>{(byStage[stage.id] ?? []).map(deal => <div key={deal.id} draggable onDragStart={e => e.dataTransfer.setData('deal', String(deal.id))} className="cursor-grab rounded-lg border bg-background p-3 shadow-sm active:cursor-grabbing"><div className="flex items-start gap-2"><GripVertical className="mt-1 h-4 w-4 text-muted-foreground"/><div className="min-w-0 flex-1"><p className="font-medium">{deal.title}</p><p className="text-sm font-semibold text-primary">{Number(deal.value).toLocaleString()} YER</p><p className="truncate text-xs text-muted-foreground">{deal.customer?.name || deal.lead?.name || 'بدون عميل'}</p></div></div></div>)}</CardContent></Card>)}</div>}
    {tab === 'leads' && <Card><CardHeader><CardTitle>العملاء المحتملون</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{leads.map(item => <div key={item.id} className="rounded-lg border p-4"><div className="flex justify-between"><p className="font-semibold">{item.name}</p><Badge variant="outline">{item.status}</Badge></div><p className="text-sm text-muted-foreground">{item.company || 'بدون شركة'}</p><p className="mt-2 text-xs">{item.phone || 'لا يوجد هاتف'}</p></div>)}</div></CardContent></Card>}
    {tab === 'activities' && <Card><CardHeader><CardTitle>Timeline</CardTitle></CardHeader><CardContent className="space-y-3">{activities.map(item => <div key={item.id} className="border-r-2 border-primary pr-3"><div className="flex items-center gap-2"><Badge>{item.type}</Badge><span className="font-medium">{item.subject || 'نشاط CRM'}</span></div><p className="text-sm text-muted-foreground">{item.body}</p><p className="text-xs text-muted-foreground">{item.occurred_at}</p></div>)}</CardContent></Card>}
    {tab === 'email' && <div className="space-y-4"><Card><CardHeader><CardTitle>إرسال بريد للعميل</CardTitle></CardHeader><CardContent className="max-w-2xl space-y-4"><div><Label>العميل</Label><select className="mt-1 flex h-10 w-full rounded-md border bg-background px-3 text-sm" value={email.customer_id} onChange={e => setEmail({...email, customer_id:e.target.value})}><option value="">اختر العميل</option>{customers.filter(item => item.email).map(item => <option key={item.id} value={item.id}>{item.name} — {item.email}</option>)}</select></div><div><Label>قالب جاهز</Label><select className="mt-1 flex h-10 w-full rounded-md border bg-background px-3 text-sm" value={email.template_id} onChange={e => useTemplate(e.target.value)}><option value="">بدون قالب</option>{templates.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><Label>العنوان</Label><Input value={email.subject} onChange={e => setEmail({...email, subject:e.target.value})} placeholder="متابعة العرض المرسل"/></div><div><Label>المحتوى HTML أو نص</Label><textarea className="mt-1 min-h-40 w-full rounded-md border bg-background p-3 text-sm" value={email.body} onChange={e => setEmail({...email, body:e.target.value})} placeholder="مرحبًا {{customer_name}}..."/></div><Button onClick={sendEmail}>إرسال عبر Queue</Button></CardContent></Card><Card><CardHeader><CardTitle>سجل الإيميلات</CardTitle></CardHeader><CardContent className="space-y-2">{emailLogs.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-3 text-sm"><span>{item.to_email}</span><span className="flex-1 text-muted-foreground">{item.subject}</span><Badge variant={item.status === 'sent' ? 'default' : item.status === 'failed' ? 'destructive' : 'secondary'}>{item.status}</Badge></div>)}</CardContent></Card></div>}
    {tab === 'analytics' && <div className="space-y-4">{analytics && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[UsersRound,'Leads',analytics.summary.leads],[Target,'Deals',analytics.summary.deals],[TrendingUp,'Pipeline',`${analytics.summary.pipeline_value.toLocaleString()} YER`],[Percent,'Win Rate',`${analytics.summary.win_rate}%`],[MailCheck,'Email Success',`${analytics.summary.email_success_rate}%`],[Activity,'Activities',analytics.summary.activities]].map(([Icon,label,value]) => <Card key={String(label)}><CardContent className="flex items-center gap-3 p-4"><Icon className="h-5 w-5 text-primary"/><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-lg font-bold">{value}</p></div></CardContent></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Funnel المراحل</CardTitle></CardHeader><CardContent className="space-y-3">{analytics.funnel.map(item => <div key={item.name}><div className="mb-1 flex justify-between text-sm"><span>{item.name_ar || item.name}</span><span>{item.deals} صفقة — {item.value.toLocaleString()} YER</span></div><div className="h-2 rounded bg-muted"><div className="h-2 rounded bg-primary" style={{width:`${Math.min(100, item.deals * 15)}%`}}/></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>مصادر Leads</CardTitle></CardHeader><CardContent className="space-y-2">{analytics.lead_sources.map(item => <div key={item.source} className="flex justify-between rounded border p-3 text-sm"><span>{item.source}</span><span>{item.leads} Leads</span><Badge>{item.conversion_rate}%</Badge></div>)}</CardContent></Card></div><Card><CardHeader><CardTitle>الاتجاه اليومي</CardTitle></CardHeader><CardContent className="overflow-x-auto"><div className="grid min-w-[640px] grid-cols-5 gap-2 text-xs font-medium"><span>التاريخ</span><span>Leads</span><span>Deals</span><span>Activities</span><span>Email</span>{analytics.daily_trend.slice(-14).map(item => <span key={item.date} className="contents"><span>{item.date}</span><span>{item.leads}</span><span>{item.deals}</span><span>{item.activities}</span><span>{item.emails}</span></span>)}</div></CardContent></Card></>}</div>}
    <div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="flex items-center gap-3 p-4"><TrendingUp className="text-primary"/><div><p className="text-xs text-muted-foreground">إجمالي الصفقات</p><p className="text-xl font-bold">{deals.length}</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><Target className="text-primary"/><div><p className="text-xs text-muted-foreground">قيمة Pipeline</p><p className="text-xl font-bold">{deals.reduce((sum, d) => sum + Number(d.value || 0), 0).toLocaleString()} YER</p></div></CardContent></Card></div>
    <Dialog open={showLead} onOpenChange={setShowLead}><DialogContent><DialogHeader><DialogTitle>إضافة عميل محتمل</DialogTitle></DialogHeader><div className="space-y-3"><Label>الاسم *</Label><Input value={lead.name} onChange={e => setLead({...lead, name:e.target.value})}/><Label>الشركة</Label><Input value={lead.company} onChange={e => setLead({...lead, company:e.target.value})}/><Label>الهاتف</Label><Input dir="ltr" value={lead.phone} onChange={e => setLead({...lead, phone:e.target.value})}/><Label>البريد الإلكتروني</Label><Input dir="ltr" value={lead.email} onChange={e => setLead({...lead, email:e.target.value})}/><Button className="w-full" onClick={createLead}>حفظ</Button></div></DialogContent></Dialog>
  </div>;
}
