name: CI/CD React App to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: 76.13.50.208
            REMOTE_USER: ubuntu
            REMOTE_PORT: 22
            SOURCE: build
            TARGET: /www/wwwroot/erpzin